### ISSUE TITLE
chore(installer): add new dependencies to the installers

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1001]
since Blink was added to Warp, Opus is required. The installers for linux/mac/windows need to be updated to specify this dependency.

**Comment by dariusc93** [comment]
Was this resolved with https://github.com/Satellite-im/Uplink/pull/1000 

CC @sdwoodbury

**Comment by phillsatellite** [comment]
Can I close since we merged #1065 

cc: @sdwoodbury

**Comment by stavares843** [comment]
update: darius asked stu, stu said its not resolved

**Comment by sdwoodbury** [comment]
I believe Windows just needs this environment variable set: `OPUS_STATIC`.  edit: seems like the current windows build process is OK even without this. 
On Linux, `ui/deb/DEBIAN/control` has a `Depends` section which specifies opus :+1: 
on Mac, `otool -L uplink` didn't show any symlinks to opus. maybe it doesn't need it. 

I did however find that similar work is needed for `libaom` - the video codec.

**Comment by dariusc93** [comment]
Is this still ongoing? 

CC @sdwoodbury
