### ISSUE TITLE
bug(markdown): Spaces appear as "&nbsp;" w/ markdowns

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1012]
**Issue:**
When you paste code into the chat and wrap it in `` any spaces used for that code will have "&nbsp;" 

**OS:**
All

**Screenshot:**
![image](https://github.com/Satellite-im/Uplink/assets/93608357/39fa3558-7c19-4fae-bb5c-ecedd34deca8)

**Comment by tooshel** [comment]
Confirmed! 
![image](https://github.com/Satellite-im/Uplink/assets/223338/f9656253-df3d-48fc-a54f-b778f4ee3fa9)

**Comment by tooshel** [comment]
Phill to deep dive into this and add a few more items.

**Comment by tooshel** [comment]
Matt has this fixed in a future PR.

**Comment by tooshel** [comment]
![image](https://github.com/Satellite-im/Uplink/assets/223338/60fee48a-fc0b-4374-b06f-8b6c55b6a92e)
