### ISSUE TITLE
feat(chats): Generate user card when sending DID in messages

### ISSUE THREAD

**Issue by XileHorizon** [Satellite-im/Uplink#1014]
Task: Generate a user card when DID is sent to another user(s)

The user card should work like any other embed and be wrapped in the chat bubble it was sent with. The DID should be collapsed in the message if there is other text present but should only display the user card if there is no other text with the DID. The card should have a user profile picture, banner, and name. It should also have two buttons, one to message the user and the other to add the user. If the user is already a friend or you have sent a request to the user, the button should be greyed out and have a tooltip saying something like "user is already your friend!" or "request sent!"

Reference:
<img src="https://user-images.githubusercontent.com/33043119/254686696-f66ea412-6773-4db4-87a7-0857873c8b94.png" width="200"/>
<img src="https://user-images.githubusercontent.com/33043119/254686815-2ef855ad-100d-4918-98be-eb913d8e5291.png" width="200"/>

<img src="https://github.com/Satellite-im/Uplink/assets/33043119/17f1394a-3564-4ee1-aa5e-8ab40cd2f2c5" width="200"/><br />

<img src="https://github.com/Satellite-im/Uplink/assets/33043119/8e59988f-af21-4c44-9deb-7c51f197b032" width="400"/>

Figma Mockup:
https://www.figma.com/file/GrAhLmQWA2kfD1Nw9nd24m/Chats-%2F-Landing-Page?type=design&node-id=1181-44044&mode=design&t=MvWROTEq4sCcxnjH-4

**Comment by stavares843** [comment]
same as https://github.com/Satellite-im/Uplink/issues/1255

**Comment by stavares843** [comment]
and flem added a PR for it here
https://github.com/Satellite-im/Uplink/pull/1300
