### ISSUE TITLE
bug(chat): If too many files are attached to a message, it will never send 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1026]
**Issue:**
Like the title says, within chat if you send a message with attachments but you attach too many files to it they will never send or appear in chat 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/9400178b-0902-453e-9029-e1ff429161ee

**Comment by dariusc93** [comment]
This isnt a bug but an intentional limit. If its more than 8 files it will return an error and not send the files. Its in place temporarily

**Comment by phillsatellite** [comment]
> This isnt a bug but an intentional limit. If its more than 8 files it will return an error and not send the files. Its in place temporarily

hmm I never got the error to appear. Let me dig a little deeper maybe scope of the ticket just needs changed
