### ISSUE TITLE
bug(chat): sending __a__ only sends a___

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1027]
STR:
- go to chat
- send __a__
- only sends a___

<img width="245" alt="Captura de ecrã 2023-07-21, às 21 58 58" src="https://github.com/Satellite-im/Uplink/assets/29093946/2a011c86-efaa-498f-b6f8-af531a0781a3">
<img width="170" alt="Captura de ecrã 2023-07-21, às 21 59 04" src="https://github.com/Satellite-im/Uplink/assets/29093946/89659c09-0659-4ec2-bd8d-fdd810b45434">

dev

macOS

**Comment by phillsatellite** [comment]
Closing ticket 

https://github.com/Satellite-im/Uplink/assets/93608357/64181f99-98b9-416b-aea3-30bc3e04e96e
