### ISSUE TITLE
bug(images): sending a image without background appears green in the app

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1037]
STR:
- go to chat
- send a image without background example

![Auchan-Logo](https://github.com/Satellite-im/Uplink/assets/29093946/13df3aa5-f4d5-465c-913c-6e5dfd346832)

in the app shows as green

![image](https://github.com/Satellite-im/Uplink/assets/29093946/63461db8-d86c-4309-9d24-dd1fa83a543e)

macOS, m1

**Comment by dariusc93** [comment]
I wonder if this is related to the thumbnail generation. Does it appear the same way under the Files section?

**Comment by stavares843** [comment]
yes

A terça, 25/07/2023, 18:39, Darius Clark ***@***.***>
escreveu:

**Comment by lgmarchi** [comment]
It is about how thumbnail is generated when we upload files in chats or Storage, @dariusc93 is taking a look on it as well on Warp side.

**Comment by dariusc93** [comment]
After some testing, this looks to be related to uplink. Possibly CSS changing the background though from my knowledge this seems to only affect thumbnail images.

**Comment by stavares843** [comment]
is no longer green but the theme is not properly applied when is the light theme will add a new issue for it
