### ISSUE TITLE
bug(chat): lacking padding in count char

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1058]
STR:
- go to chat
- count char is lacking padding

<img width="1062" alt="Captura de ecrã 2023-08-01, às 17 17 46" src="https://github.com/Satellite-im/Uplink/assets/29093946/506ed923-9fbc-488e-82bd-0c56890faa8e">

macOS, m1

**Comment by Flemmli97** [comment]
is this still the case in newest dev branch? i have some padding on my end

**Comment by stavares843** [comment]
<img width="652" alt="Captura de ecrã 2023-08-04, às 12 55 06" src="https://github.com/Satellite-im/Uplink/assets/29093946/8a46be6e-2fb8-49d8-8f7c-6359c25c0504">

latest dev

macOS
