### ISSUE TITLE
bug(extensions): emoji extension not opening on Linux

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1064]
The extension is detected by uplink and the button appears but clicking the emoji button doesn't open the menu. 

edit: doesn't work on Mac either

**Comment by dariusc93** [comment]
I have been able to open the menu and click on the emoji without any issues under linux. Havent tried it on mac yet.

**Comment by sdwoodbury** [comment]
it's back to working again.

**Comment by sdwoodbury** [comment]
I think I figured it out - seems that if i `cargo build --package emoji_selector` then it doesn't work. but if i `cargo build` to make everything at once, then it works.

**Comment by dariusc93** [comment]
> I think I figured it out - seems that if i `cargo build --package emoji_selector` then it doesn't work. but if i `cargo build` to make everything at once, then it works.

Interesting. Does building in the crate directory not work either?

**Comment by sdwoodbury** [comment]
i'm not sure but I assume so since specifying `--package` causes all the dependencies used by that package to be re-built.
