### ISSUE TITLE
bug(macOS): Chatbox just says "say" when app is in mobile view

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1069]
**Issue:**
When you minimize the app to go into mobile view the placeholder in the chatbox just says "say" maybe we could have "say..."

Ticket will not be able to be worked on until Jeffs PR is merged #1003 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/9f2c8df2-b44f-4c17-84f4-55c42f5c9091

**Comment by tooshel** [comment]
I wonder what a reasonable width for mobile we can expect? Like, what should be the minimum?

**Comment by stavares843** [comment]
suggestions:

Enable Text Overflow Handling: Set the CSS property overflow-wrap: break-word; or word-wrap: break-word; on the container that displays the text. This will allow long words to be broken into multiple lines and avoid being cut off at the edge of the container.


Use Ellipsis for Long Text: For cases where you have limited space and the text is too long to fit, consider truncating the text and displaying an ellipsis ("...") at the end to indicate that there's more content. Users can then hover over the text to see the full string as a tooltip or click on it to open a pop-up with the complete text.
