### ISSUE TITLE
task(reactions): Add indicator showing you need to add emoji extension to use all reactions

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1083]
**Issue:**
When you dont have emoji's enabled there is no way to use all the emoji's to react to a message, we should add a message or indicator so the user is aware of this and knows to install the extension to react with all emoji's 

**Screenshot:**
![image](https://github.com/Satellite-im/Uplink/assets/93608357/0ee65dfe-963a-4cf3-a68a-fbc6af1350c1)

**Comment by luisecm** [comment]
I think the button should be hidden if emoji extension is not enabled
