### ISSUE TITLE
task(group): make group search use substring/contains

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1089]
In this task, the objective is to enhance the search functionality. The focus is on improving two specific aspects of the search feature:

**Substring Search:**
The second improvement involves enabling substring search functionality. Currently, the search system may only return results that exactly match the entire query. For example, if a user searches for "apple," the system may not retrieve results containing "apples" or "pineapples." The group needs to implement modifications so that the search engine considers partial matches within words, ensuring that results are displayed for all variations of the search query.

**Comment by WanderingHogan** [comment]
example:

    group_participants.retain(|friend| {
        return friend
            .username()
            .to_ascii_lowercase()
            .contains(&name_prefix.to_ascii_lowercase());
    });
