### ISSUE TITLE
bug(global): Users arent always appearing online 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1120]
**Issue:**
While on dev this morning I noticed that a few hours went by without any of my friends appearing online, I messaged Sara to see if she had also been testing dev this morning and she said she was. But on Uplink she never appeared online. She also said for her that I never appeared online for her. It was when we both had to close our apps and re open at the same time for one of us to appear online and messages start to go through 

**OS:**
All

**Screenshots:**
<img width="982" alt="Screenshot_2023-08-11_at_1 39 16_PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/85578aba-bc17-4421-b9b5-e7943a8a985e">
<img width="649" alt="Captura_de_ecra_2023-08-11_as_18 39 06" src="https://github.com/Satellite-im/Uplink/assets/93608357/b163e038-d4a5-414e-b4cc-976492c98405">

**Comment by dariusc93** [comment]
Could you provide any logs of this occurring? This might be related to the changes on warp side and how it handles the online indicator (havent been able to reproduce it myself yet) but seeing what goes on in the logs would be helpful.

**Comment by dariusc93** [comment]
@phillsatellite mentioned about another user now showing up online, however I will leave this ticket open for the time being

**Comment by phillsatellite** [comment]
Been testing today to try to get more logs for @dariusc93 but havent been able to replicate much (works 100% of the time when accounts are on local network) Was having the most issues with Sara but seems to be working a lot better today

**Comment by dariusc93** [comment]
Closing this as this was originally related to not being seen online but can still send messages, etc.
