### ISSUE TITLE
bug(ui): Sidebar closes when entered chat *Linux only*

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1126]
**Issue:**
When you enter a chat on Linux the sidebar will close each time 

**OS:**
Linux

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/ca1be6a6-a9b9-4cae-8cfe-d3d3cdcf6e0c

**Comment by dariusc93** [comment]
Is this only at a specific window size?

EDIT: This is seems to happen when the window is small enough. If its big or full screen, it does not happen.
