### ISSUE TITLE
chore(calling-ui-siderbar): make it look like figma

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Uplink#1135]
current:
<img width="736" alt="Screenshot 2023-08-15 at 11 13 48 AM" src="https://github.com/Satellite-im/Uplink/assets/2993032/5ec53341-2e85-46d6-be2f-a013064dd1cd">

screenshot of desired: 

<img width="411" alt="Screenshot 2023-08-15 at 11 14 33 AM" src="https://github.com/Satellite-im/Uplink/assets/2993032/3f2ff4cc-0412-456c-bbf7-9656a6058402">

<img width="449" alt="Screenshot 2023-08-15 at 11 14 56 AM" src="https://github.com/Satellite-im/Uplink/assets/2993032/008bfb2e-16b0-44e8-8e64-cc22e3d674b3">

figma link: https://www.figma.com/file/vYKm91y1PjZPW0NRuzj0u9/Video%2F-Voice-Chat?type=design&node-id=0-1&mode=design&t=2el4JshSVnT0WvPU-0

**Comment by Flemmli97** [comment]
there is a cogwheel in the call ui. what is it for? do we need that?
