### ISSUE TITLE
chore(misc): Load identity images separately

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/Uplink#1137]
In https://github.com/Satellite-im/Uplink/pull/976, warp made changes that separated pictures from `Identity`, using separate functions to fetch them. This helps improves performance in different ways (please see PR for some info). Apart of that PR, and to maintain compatibility at the time, images are fetched when the identity is fetched and stored inside the `Identity` wrapper, but long term doing this may not realistically make use of the benefits of the changes made.

Uplink should instead separate this into two task. First would be to fetch the identities (which can be left as is in its current state in warp runner) and separately (for any related identities that were loaded) to fetch their profile and banner images. This would improve loading performance in uplink since the images can be loaded separately and updated in the state accordingly.

Notes:
- The PR above to introduce 2 commands `MultiPassCmd::GetProfilePicture` and `MultiPassCmd::GetProfileBanner` that can be used to obtain pictures and banners of a related identity via `MultiPass::identity_picture` and `MultiPass::identity_banner`
- Would suggest having a separate task that would send events to update the state during the initial load. This should keep things serial while having each task polled separately unless one wish to process each request serially in a separate task.

**Comment by stavares843** [comment]
@Flemmli97 do you have a PR for this or can i move this one to the backlog repo instead?
