### ISSUE TITLE
bug(responsive): settings not properly displaying

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1146]
luis noticed the following issue

![image](https://github.com/Satellite-im/Uplink/assets/29093946/7def8a36-6b41-465e-8c49-b30ef9035492)

when resizing to this size, is not displaying properly

macOS

**Comment by Flemmli97** [comment]
do you mean the notification with "new profile"?

**Comment by stavares843** [comment]
<img width="698" alt="Captura de ecrã 2023-08-21, às 18 26 38" src="https://github.com/Satellite-im/Uplink/assets/29093946/2f2db685-5715-4f2b-9352-c90643a70207">


this section

**Comment by stavares843** [comment]
cc @Flemmli97

**Comment by Flemmli97** [comment]
im not sure what is not displaying correctly? you mean it stretching all the way? it seems to be intended for me
@stavares843

**Comment by Flemmli97** [comment]
@stavares843 i am still unsure at what exactly the bug is? how should it look like?
