### ISSUE TITLE
bug(chats): selecting a chat from the sidebar triggers mobile view

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1152]
experienced on Linux

https://github.com/Satellite-im/Uplink/assets/8636602/79869f67-4d1c-4289-b271-f9b9c6c68599

**Comment by phillsatellite** [comment]
Is this on the latest dev? Using my Linux VM I wasnt able to replicate 

https://github.com/Satellite-im/Uplink/assets/93608357/97a623f8-a193-4de5-8386-5630ff41dfa5

**Comment by lgmarchi** [comment]
> Is this on the latest dev? Using my Linux VM I wasnt able to replicate
> 
>  Screen.Recording.2023-08-22.at.11.48.05.AM.mov

Phill, I think those kind of errors, it is because pixels on screen, so not depend on OS, and it is a screen pixels problem

**Comment by dariusc93** [comment]
Relates to https://github.com/Satellite-im/Uplink/issues/1126
