### ISSUE TITLE
bug(ui): Create a group is rendered offscreen

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1160]
**Issue:**
When you open create a group it is rended offscreen to the right 

**OS:**
All

**Screenshot:**
<img width="954" alt="Screenshot 2023-08-24 at 2 34 28 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/6596c481-eed7-4a0c-9cba-5e24fae72b8c">

**Comment by stavares843** [comment]
cc @Flemmli97 @lgmarchi if you guys wanna take a look 😄

**Comment by lgmarchi** [comment]
> cc @Flemmli97 @lgmarchi if you guys wanna take a look 😄

I can take a look!

**Comment by stavares843** [comment]
thanks! 🎉
