### ISSUE TITLE
bug(emoji): emoji counter not working properly on m2

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1167]
From Phil:

So I tried on a m1 Mac and a m2 Mac. The m1 Mac worked great but on the M2 I had an issue of the emoji counter wouldn't show count until after you insert the emoji. The count would not clear out again until after you send another message with an emoji 

https://github.com/Satellite-im/Uplink/assets/93608357/f228f8cb-cb22-4a9a-84a5-b2a72e1494c5

**Comment by luisecm** [comment]
I noticed the following:

1. If you send a message the chars counter is not reset to 0 (happened on Windows)
2. If you send a message the chars counter starts to show 0/1024/1024 (happened on MacOS)


https://github.com/Satellite-im/Uplink/assets/35935591/7856fa1b-e31e-4f82-bdc4-59a7f1e30efd

**Comment by stavares843** [comment]
also reproduced here the 
> If you send a message the chars counter starts to show 0/1024/1024 (happened on MacOS)
