### ISSUE TITLE
bug(ui): code markdowns messages are not displayed correctly on sidebar preview

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#1210]
When the last message contains a code language markdown, the sidebar preview for this message is displayed incorrectly (not text displayed at all, just a black box)

Seen on MacOS:

Steps to replicate:
1. Login with an account with friends
2. Go to a chat conversation
3. Send a message using the code markdown (like this):
\```javascript
let a = 1 + 1;

4. The last message sent displayed on sidebar preview is shown as a "spoiler" message instead of showing the text from the last message (let a = 1 + 1);

![image](https://github.com/Satellite-im/Uplink/assets/35935591/e033809d-e5f5-41b0-9f32-f1ff1ba327ca)

**Comment by stavares843** [comment]
still happens

<img width="793" alt="Captura de ecrã 2023-11-06, às 22 10 24" src="https://github.com/Satellite-im/Uplink/assets/29093946/55464ce3-e59d-42bc-ba75-510d5085d9fd">

**Comment by lgmarchi** [comment]
It was closed, mainly because we decided to not show messages with markdown in sidebar.

**Comment by stavares843** [comment]
👍
