### ISSUE TITLE
bug(Groups): Group invalid error when name is correct 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1211]
**Issue:**
If you do these steps below you will receive an error that group name is incorrect when it is not 

-Select members of the group
-Type in name of group 
-Hit enter on keyboard 
-Select "Create Group"

**OS:**
All 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/e11c74b7-74f9-498d-9f91-75dbfc7f3d26

**Comment by stavares843** [comment]
no longer happens
