### ISSUE TITLE
feat(settings): add ability to change online status

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1215]
**Task:** Just like in Core we want to let the User have the ability to change they're online status. This was located at the bottom of the sidebar, if the User clicked they're avatar a menu would appear with the option to log out of the app and also to change the online status to _Online_ , _Away_ , _Busy_ , _Offline_

**Screenshot**
<img width="706" alt="Change Status " src="https://user-images.githubusercontent.com/93608357/216456804-42c792aa-364f-4aac-81e2-b4844ca3cef9.png">

**Comment by XileHorizon** [comment]
I made up some designs for the online status: https://www.figma.com/file/rDRlZgiZb2jOeqWKapkeMH/Settings?type=design&node-id=1036-23415&mode=design&t=zhaSGKTbLrWqcvrI-4
