### ISSUE TITLE
bug(macOS): App will crash when building dmg - sonoma only

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1239]
**Issue:**
Seems to be a new problem with Sonoma. On MacOS if you do `make dmg` then go to Uplink/Target/Release/MacOS and open up the app it will be stuck on the chat page. When you close the app and re open it will crash at the PIN page 

**OS:**
MacOS 

**Screen recording:**
<img width="1008" alt="Screenshot 2023-09-22 at 1 00 14 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/a1272c58-b23f-47bb-b2c6-601c92ff7248">

https://github.com/Satellite-im/Uplink/assets/93608357/14a24c31-034e-497f-aded-536cb111d4d1

**Comment by luisecm** [comment]
Happens in my mac with Sonoma too! Seems like its happening only with the builds created with make dmg. I tried downloading the app published in our website and it is working fine

**Comment by Flemmli97** [comment]
tested on macos ventura: does not happen there so its prob caused by the new os

**Comment by phillsatellite** [comment]
https://github.com/Satellite-im/Uplink/pull/1358 fixed here
