### ISSUE TITLE
bug(windows): App sometimes crashes after typing PIN in

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1243]
**Issue:** 
On Windows if you log into the app after typing in your PIN you will sometimes get a crash. When this happens you get this error in the terminal 

error: process didn't exit successfully: target\release\uplink.exe (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

Ive noticed I only get this error/crash when I run _without_ the trace2 

**OS:**
Windows

**Comment by phillsatellite** [comment]
I've noticed to replicate this crash each time you can do this flow 

-On Windows 11 doing cargo run with or without the release flag 
-Type in PIN go to Settings/Developer/Turn on Developer Mode 
-Close app 
-Re open and type in PIN 
-App will crash with 

```error: process didn't exit successfully: target\release\uplink.exe (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)```

**Comment by tooshel** [comment]
This was fixed when we merged in a branch from Evan (https://github.com/ealmloff/dioxus/tree/uplink-fork) to our Dioxus fork but it caused other bugs (around creating groups and file folders) so we had to undo it. The plan is to wait for Dioxus to get to a stable state and switch back to the an official Dioxus release. Once that's done a new task of "migrating to Diouxs 0.5" should fix this issue.

**Comment by stavares843** [comment]
@tooshel @phillsatellite do you still have this issue?

**Comment by phillsatellite** [comment]
I do not on Windows 11 we can close unless @tooshel still has it

**Comment by stavares843** [comment]
closing @tooshel if this still happens for you let us know
