### ISSUE TITLE
chore(chatbar): disabling the chatbar when it's loading instead of displaying different text and not being multi line by default

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1254]
Should change to just disabling the chatbar when it's loading instead of displaying different text. Should also not be multi-line by default.

![image](https://github.com/Satellite-im/Uplink/assets/29093946/dded0f3f-f417-4e16-9191-c4a083368283)

**Comment by phillsatellite** [comment]
Ive also noticed that the multi-line is only on by default if the user has extensions toggled on 

**Emoji extensions toggled on:**

https://github.com/Satellite-im/Uplink/assets/93608357/f3e0298d-8418-49ce-97c2-4e2187cabc81

**Emoji extensions toggled off:**

https://github.com/Satellite-im/Uplink/assets/93608357/4321807b-5fc8-4789-a808-74fb4d3d42f7
