### ISSUE TITLE
bug(files): Files are not downloading properly 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1262]
**Issue:**
On all OS's there seems to be issues downloading files 

**MacOS:**
When you download a file from chat it will take a really long time to appear at save location and when you try to open it, it asks you to search the app store for a app to open that unknown filetype or it will say file is empty 

https://github.com/Satellite-im/Uplink/assets/93608357/ddaa169b-5a82-4d53-b71d-0ab6fde7c048

https://github.com/Satellite-im/Uplink/assets/93608357/310565b2-ba96-48cc-af37-2c79582ad2ed

<img width="260" alt="filempty" src="https://github.com/Satellite-im/Uplink/assets/93608357/7620dbc7-2626-4287-96e0-413e87e6643f">

**Windows:**
When you try to download the file from chat, it doesn't recognize the file type and will not save

https://github.com/Satellite-im/Uplink/assets/93608357/67eef8da-37f1-4985-8689-7e36ed81ec02

**Linux:**
Not sure if this is the true behavior since I am on a vm but it also takes a long time to appear at save location, when I tried to open the file in Linux it took me to a text editor 

https://github.com/Satellite-im/Uplink/assets/93608357/34788a0c-3bed-417d-a952-dcd648f64451

https://github.com/Satellite-im/Uplink/assets/93608357/0216e224-7a8f-4d0b-85e1-fd501a8c83b5

**Comment by lgmarchi** [comment]
@phillsatellite I didn't have this problem on dev, could you test again please?

**Comment by stavares843** [comment]
@lgmarchi removed you because darius fixed this in his PR
https://github.com/Satellite-im/Uplink/pull/1288
