### ISSUE TITLE
chats aren't displayed

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#127]
https://user-images.githubusercontent.com/8636602/212094358-c13b7f8c-756a-4761-b813-dcbaa95de9aa.mp4

**Comment by phillsatellite** [comment]
Is this on dev with the latest changes? I haven't been able to replicate
 
https://user-images.githubusercontent.com/93608357/212102395-a22eefcf-a2a0-410e-9d4d-3c79ede0b9b6.mov

**Comment by sdwoodbury** [comment]
yes. i deleted the `.uplink` directory to be sure. perhaps this is a platform specific issue. 

edit: I commented out the titlebar and still had this problem. now i'm not sure where it came from.

**Comment by sdwoodbury** [comment]
![image](https://user-images.githubusercontent.com/8636602/212109608-c3533eba-f609-4846-8214-852103903095.png)
another possible problem. the navbar is spread out on the friends and files pages. that looks funny,

**Comment by phillsatellite** [comment]
> ![image](https://user-images.githubusercontent.com/8636602/212109608-c3533eba-f609-4846-8214-852103903095.png) another possible problem. the navbar is spread out on the friends and files pages. that looks funny,

I have a ticket for this already here https://github.com/Satellite-im/Uplink/issues/128 , I also have a few more in the backlog that deal with the sidebar / nav bar. And noted I'll try again and see if I can get it to appear on my side

**Comment by sdwoodbury** [comment]
i'm pretty sure it's from #122. I found that if i undid the changes to `ui/src/layouts/chat.rs`, it worked as expected. the problem was that the `Welcome` element wasn't being displayed, due to this logic: 

```
(state.read().ui.is_minimal_view() && state.read().ui.sidebar_hidden || !state.read().ui.is_minimal_view()).then(|| rsx!(
    state.read().chats.active.is_some().then(|| rsx! (
        Compose {}
    )),
    state.read().chats.active.is_none().then(|| rsx! (
        Welcome {}
    ))
))
```

**Comment by sdwoodbury** [comment]
i'm using a 27" monitor (technically 2). perhaps that's the reason i saw the bug and others didn't.
