### ISSUE TITLE
task(ui): Context menu for Inspect Elements could be displayed only when developer mode is on

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#1270]
Currently all users can right click on the app and see the Context Menu for Inspect Element. Brought this to the QA team and we agreed that it would be good that only users with Developer Mode can see this context menu, instead of all users.

Tested on: MacOS latest dev

Prerequisites:
Account created

Steps to reproduce:

1. Login to the app
2. Go to settings and ensure that the current user has Developer Mode disabled
3. Right click on any part of the app
4. Reload/Inspect Elements context menu is shown for the user

Video:
https://github.com/Satellite-im/Uplink/assets/35935591/25943ade-67c3-4536-bccc-93efbedbd552

**Comment by Flemmli97** [comment]
this is solved in #1248 which is not merged yet

**Comment by lgmarchi** [comment]
> this is solved in #1248 which is not merged yet

Good to know, thanks my friend
