### ISSUE TITLE
bug(files): On share files "chats" is cutoff and names are missing from list 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1279]
**Issue:**
When you go to 

-Files page 
-Share Files 

The word _Chats_ will be cutoff and the names will be missing from the list of chats 

**OS:**
All

**Screenshot:**
<img width="977" alt="Screenshot 2023-10-03 at 1 50 29 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/d60d8664-a0d3-4f61-9bc3-228c0a8d25c4">

**Comment by lgmarchi** [comment]
@phillsatellite Names of the list, I fixed already in one of the PRs, I will fix chats as well to not cut now
