### ISSUE TITLE
App stays in mobile/desktop view when adjust browser size

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#128]
**Issue:** If you are in mobile view and adjust your browser window to be bigger like the desktop view, the UI will still be rendered like you are in mobile view. This is the same if you are in desktop view and you adjust the browser window to be smaller like the mobile view, the UI will still be rendered for desktop view and not mobile. 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/212104843-761c162f-e62c-44db-b6ff-9b95ee49600c.mov

**Comment by lgmarchi** [comment]
This ticket needs to wait Dioxus PR update

**Comment by phillsatellite** [comment]
Tested on WindowsOS and MacOS and works as should from Matts last PR 👍
