### ISSUE TITLE
bug(general): Pasting from clipboard will paste twice or 4 times

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1286]
**Issue:**
When you copy an imagine from clipboard and paste it into chat, it will paste twice. On Windows it will paste it 4 times

**OS:**
Windows 
MacOS 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/897fed8d-c1ce-4139-97cb-e15b355ee10b

**Comment by stavares843** [comment]
works fine on my macOS

**Comment by lgmarchi** [comment]
@phillsatellite In macOS is working fine, can you replicate this problem?

**Comment by stavares843** [comment]
works on my mac but sheldon and phil were able to reproduce

**Comment by lgmarchi** [comment]
> works on my mac but sheldon and phil were able to reproduce

Interesting, I will talk to both.
