### ISSUE TITLE
bug(chats): group chat has indicator online/offline should is not needed

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#1293]
Update:
Indicator Online/Offline for the group chat is not required. Therefore, group chat on sidebar and on the chat screen topbar should not display an indicator of online/offline

Prerequisites: 
At least 3 accounts that are friends between each other and a group chat with the same 3 users

Environment: MacOS

Steps to reproduce: 
1. Create a group chat with the 3 accounts
2. Login with one user and ensure the other 2 users from the group are offline
3. Go to sidebar and validate the indicator online for the group (it should be offline but appears as online)
4. Chat screen topbar however shows the group is offline
5. Go to edit group to see the current status of the members of the group

Video:

https://github.com/Satellite-im/Uplink/assets/35935591/582f6252-307d-488c-9ea3-fe402f939015

**Comment by stavares843** [comment]
i'd say we ditch the indicator 🔨 

never saw any app with ''a group online'', the users in that group may be online not the group itself 😂

**Comment by luisecm** [comment]
As per @InfamousVague comments, it is better to ditch the indicator since we already can see who is online/offline by viewing the group details. Updating Issue name

**Comment by dariusc93** [comment]
I agree with sara. For group chats, there shouldnt be any online/offline indicator in the sidebar or topbar since its a chat with multiple people. The drop down list showing the indicators are more than enough
