### ISSUE TITLE
bug(ui): CreateGroup modal is broken 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1295]
**Issue:**
Create a group modal seems to be broken. _Group name_ and _Users_ are both hidden behind boxes, and none of the names on the list appear 

**OS:**
All

**Screenshot:**
<img width="401" alt="Screenshot 2023-10-06 at 12 37 21 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/f39e1738-1104-4939-b2a3-3a619c0e3859">

**Comment by luisecm** [comment]
![image](https://github.com/Satellite-im/Uplink/assets/35935591/b578af71-ea54-4c18-97b7-1ec440c2b361)

1. The input error message is covering the labels
2. Usernames are not displaying
3. Labels for group name and users input are behind the input boxes

**Comment by stavares843** [comment]
cc @Flemmli97 or @lgmarchi if any of you could take a look pls 🔨
