### ISSUE TITLE
Settings - Clicking on / under toggle switches will underline it

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#131]
**Issue:** On Linux some toggle switches will cause a grey box under neath them when trying to use

- Call Timer 
- Extension's Toggle
- Settings Toggle in Notifications 

**OS:**
Linux
MacOS

**Screen recording:** 

https://user-images.githubusercontent.com/93608357/218857224-12b7e88a-71ca-4d86-a4df-d2f02295613b.mov

<img width="1219" alt="Screenshot 2023-03-03 at 12 36 42 PM" src="https://user-images.githubusercontent.com/93608357/222789389-d523c536-1009-4251-88e2-41027f4f4da2.png">

**Comment by stavares843** [comment]
tested and wasnt happening here

if happens for you @phillsatellite reopen pls 🔨
