### ISSUE TITLE
bug(linux): Profile picture is cutoff or sometimes missing 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1314]
**Issue:**
When you crop your profile picture on Linux, sometimes the picture will be either missing entirely or just cut off 

**OS:**
Linux 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/583d30d5-77d5-4892-b4bf-bd753f835947

**Comment by stavares843** [comment]
also saw that in the chats list

<img width="88" alt="Captura de ecrã 2023-10-12, às 01 33 09" src="https://github.com/Satellite-im/Uplink/assets/29093946/a68325b0-86ce-4860-9ac7-f1b6789b1981">


macOS

**Comment by dariusc93** [comment]
resolved in https://github.com/Satellite-im/Uplink/pull/1317
