### ISSUE TITLE
bug(scroll to bottom): button doesn't always disappear

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1318]
documented here: https://github.com/Satellite-im/Uplink/pull/1307

**Comment by phillsatellite** [comment]
Just wanted to add some notes to this 

**On any OS:** 
Send an image in chat along with other messages (enough that you can scroll)
Scroll up until _Scroll to bottom_ button appears 
Scroll back down to the bottom of the chat 
Unless you click the button the _scroll to bottom_ button will persist

**Comment by phillsatellite** [comment]
11/6/23 still an issue across all OS's
