### ISSUE TITLE
bug(favorites): heart button on top of chats screen for Favorites is not modified to Add/Remove quickly

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#1319]
Description: The tooltip for Favorites button on top from Chats Screen will always show "Add to Favorites". It looks like the heart button is taking too much time to change to Add/Remove after the latest commit to Dev.

Environment: MacOS and Windows

Prerequisites:
Having an account with friends

Steps to Reproduce:
1. Login with account with friends
2. Go to any chat that is not Favorite
3. Hover on the heart button at the top. It will show a tooltip with text "Add to Favorites"
4. Click on the Heart button and user will be added as Favorite on Slimbar
5. Hover again on the heart button at the top. You will see that the button was not updated and tooltip is still the same

Expected Result: "Remove from favorites" tooltip should be displayed and Button should change to Remove from favorites
Actual Result: "Add to Favorites" tooltip is still displayed even if user is already favorited and button is still the same (Add To Favorites)

Video:
https://github.com/Satellite-im/Uplink/assets/35935591/c31dea48-a3e4-4dbc-8ff6-5f5b66eab14d

**Comment by sdwoodbury** [comment]
so strange 
![image](https://github.com/Satellite-im/Uplink/assets/8636602/8e09ae03-6f65-4667-ba43-055d53bc0406)

![image](https://github.com/Satellite-im/Uplink/assets/8636602/0ad91ce8-3b69-4eb8-a9a4-6b22ab65f0c5)

A favorite was loaded from the State.json file but it still isn't showing up in the sidebar.

**Comment by luisecm** [comment]
I noticed that if you:
1. Add to favorites
2. Then, just switch to another chat
3. Return quickly to the conversation that was just added to favorites, then you will see the heart button/tooltip updated

(same happens with pinning messages, opening reply modal and updating name of group chat) 
Like if the elements from top are not refreshing quickly, and only when loading again the conversation all is loaded fresh
