### ISSUE TITLE
bug(chats): after renaming a group chat or removing someone from group, changes are not displayed on top

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#1328]
Description: After renaming a group chat, the name displayed on top of chat is still the same. Change can be seen after waiting for some time and not quickly as before
I noticed that this bug happens also when you remove someone from the group, the text "Members (#)" is not refreshed quickly and keeps showing the same number of members as before removing the user from the group

Note: On sidebar, the new name for the group is displayed right after changing it

Environment: MacOS and Windows

Prerequisites:
Having an account with chats with group chat

Steps to Reproduce:
1. Login with account with friends
2. Go to any group chat
3. Click on Edit Group button
4. Type a new name for the group and press enter to save
5. Close edit group modal by clicking again on Edit Group button

Video:
https://github.com/Satellite-im/Uplink/assets/35935591/df1bff0c-4a5f-4859-a8b0-df867c865b7b

**Comment by Flemmli97** [comment]
was fixed in #1329.
works for me now. maybe someone else also test this before closing this issue?
