### ISSUE TITLE
bug(chat): User needs to scroll down to see timestamp 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1333]
**Issue:**
 User has to scroll down to see the timestamp of the message they just sent 
 
 **OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/9933ee0f-49ab-4df7-94c0-e84d2e34e331

**Comment by stavares843** [comment]
also happens here

macOS, m1
