### ISSUE TITLE
for release

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1337]
# to fix before release
- ~~the typing indicator is missing from the chatbar~~
-~~reactions showed up on the wrong side of the screen~~
- need to test incoming calls while a call is in progress

# todo later
- display missed calls
- handle audio degradation event - such as with a toast

**Comment by phillsatellite** [comment]
On Mac Linux and Windows I could not replicate the reactions appearing on the wrong side of the screen 

<img width="393" alt="Screenshot 2023-10-16 at 7 24 26 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/6c85ea76-7407-48e9-8d9c-3e3e112ca206">

<img width="526" alt="Screenshot 2023-10-16 at 7 24 20 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/2eec0ede-b6d3-40af-a310-051713ca29bf">

**Comment by sdwoodbury** [comment]
@phillsatellite  you're right. it just looked funny when the other side has a message as wide as the screen and the reaction appears all the way on the left. but that's as intended - not a bug.
