### ISSUE TITLE
bottom navbar shows on files page

### ISSUE THREAD

**Issue by Jekrimo** [Satellite-im/Uplink#1342]
issue:
bottom navbar shows on files page. I guess we should probably just disable sidebar in mobile view and should fix (hopefully) a few of these tickets.
screenshot:
![image](https://github.com/Satellite-im/Uplink/assets/19398153/95efb791-69cf-4410-98e4-30f8fb058653)

**Comment by tooshel** [comment]
This is covered when we fix the issues around the double navbar right @Jekrimo? Closing for now but open again if I got it wrong!

https://github.com/Satellite-im/Uplink/issues/1347

**Comment by Jekrimo** [comment]
> This is covered when we fix the issues around the double navbar right @Jekrimo? Closing for now but open again if I got it wrong!
> 
> #1347

Quite right good chap!
