### ISSUE TITLE
App window buttons and release info crowded on Windows OS

### ISSUE THREAD

**Issue by Jekrimo** [Satellite-im/Uplink#1343]
Issue: 
App window buttons and release info crowded on Windows Os
Screenshot:
![image](https://github.com/Satellite-im/Uplink/assets/19398153/54775499-3e1c-4dae-b81c-528a22d63068)
Comments:
Mac os looks good so I'm sure most linux will

**Comment by stavares843** [comment]
fixed here https://github.com/Satellite-im/Uplink/pull/1550
