### ISSUE TITLE
bug(mobile): Navbar not sticking on friends page Mac

### ISSUE THREAD

**Issue by Jekrimo** [Satellite-im/Uplink#1345]
Issue: 
Navbar not sticking on friends page Mac os. Windows seems fine currently.

Screenshot:
<img width="309" alt="Screenshot 2023-10-17 at 12 45 57 PM" src="https://github.com/Satellite-im/Uplink/assets/19398153/8f7a5644-047c-47cf-ad59-a942ffec85f1">

**Comment by stavares843** [comment]
still happens

**Comment by tooshel** [comment]
This will be fixed when we do https://github.com/Satellite-im/Uplink/issues/1347 . . . so closing.
