### ISSUE TITLE
chore(mobile): make the extensions page buttons in a vertical list instead

### ISSUE THREAD

**Issue by Jekrimo** [Satellite-im/Uplink#1348]
Issue:
settings extensions page table doesn’t scroll. Darius mentioned we may need to disable extensions entirely for ios, reference -> https://github.com/Satellite-im/Uplink-Deprecated/issues/457

Screenshot:
![image](https://github.com/Satellite-im/Uplink/assets/19398153/db878b6f-2769-4376-b483-e4771170bdae)

**Comment by stavares843** [comment]
still happens

a quick fix would just be listing the buttons in the vertical instead also, is easier to use and is prettier vs the horizontal one

**Comment by stavares843** [comment]
<img width="265" alt="Captura de ecrã 2023-11-07, às 17 52 52" src="https://github.com/Satellite-im/Uplink/assets/29093946/38ba64c2-73bc-481c-9e99-1942865d20ea">


i meant these buttons
