### ISSUE TITLE
bug(calling): When User goes to Settings during call/mic cuts out

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1349]
**Issue:**
While Sheldon and I were on a call today, he was coming through super clear but each time he would navigate to the Settings page his mic would cut out and I could no longer hear him until he returned to our chat 

**OS:**
I was on MacOS 14 while Sheldon was on Windows 10

**Comment by sdwoodbury** [comment]
could not reproduce.
