### ISSUE TITLE
Create dev logger

### ISSUE THREAD

**Issue by lgmarchi** [Satellite-im/Uplink#135]
A utility class called "Logger" which will accept log messages with four different levels (debug, warn, info and error). It should add the errors as structs like Error { level: ErrorLevel, message: String } then push the message to a log in memory. it should also write to a debug.log in .uplink folder. Lastly we should make a component which we can open in a new window which shows the log in a scrolling "pre" element so we can browse the log while running the app

**Comment by dariusc93** [comment]
One could take libraries like `tracing` or `log`  and make a hook into that instead to capture the log messages and pass it into whatever it needs to be (while also possibly utilizing eg `tracing` to log to a file, or if `log` is used, to append to a single file). Do note though, outputting logs can generate a lot of data so its best not to log every single crate or dependency from a level, but instead be more specific in the crates being logged, rotate the files once it hits a specific size, and if the messages are being buffered in a component to flush them out regularly, especially if the logs in memory going to be persistent.
