### ISSUE TITLE
bug(chat): clicking on url on pinned messages doesnt work

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1383]
STR:
- go to chat
- send a message with a link
- pin that messages
- go to pinned messages
- click on url
- doesn't do anything

<img width="523" alt="Captura de ecrã 2023-10-23, às 22 09 11" src="https://github.com/Satellite-im/Uplink/assets/29093946/1dda027a-b0ac-4f90-b916-ba4983efa276">

macOS, m1

**Comment by Flemmli97** [comment]
hmm. tested on m2 and it works there.
i also tested on linux and it works too

**Comment by stavares843** [comment]
works fine now

cc @phillsatellite does it also work in your side?

closing please reopen if any bugs 😂
