### ISSUE TITLE
Chat - Video icon missing when in Mobile view

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#139]
**Device:**
- Mobile 

**Issue:**
- While in a chat in mobile view, the video call button will be missing 

**Screenshots:**

<img width="301" alt="Screenshot 2023-01-13 at 12 37 19 PM" src="https://user-images.githubusercontent.com/93608357/212384317-adb935e0-6139-41b7-9db8-12221b8114ca.png">

<img width="949" alt="Screenshot 2023-01-13 at 12 36 50 PM" src="https://user-images.githubusercontent.com/93608357/212384330-3e7e8261-6ef8-4038-ae7f-4dcf54efb443.png">

**Comment by sdwoodbury** [comment]
it appears that this was done on purpose. it's easy enough to change it, the question is should we.  @InfamousVague? 
![image](https://user-images.githubusercontent.com/8636602/216452801-d4299c5d-41f9-4960-867b-560ad1958371.png)
