### ISSUE TITLE
bug(chat): User cannot select from list on Create Groups

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1390]
**Issue:**
When the User tries to select from the list on Create Groups, modal will close 

**OS:**
Mac
Linux

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/f3d07604-f0a5-4c0d-9100-4ca01d62f92d

**Comment by stavares843** [comment]
these three tickets may be related, so if you find a fix consult the other tickets, too
 
 https://github.com/Satellite-im/Uplink/issues/1384
https://github.com/Satellite-im/Uplink/issues/1374

**Comment by stavares843** [comment]
fixed here https://github.com/Satellite-im/Uplink/pull/1393
