### ISSUE TITLE
bug(profile): Profile picture is blank when adding friends

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1401]
**Issue:**
Something with profile pictures recently broke, when you add someone instead of showing either their profile picture or the default Uplink photo its appearing as blank 

**OS:**
All

**Screenshot:**
<img width="327" alt="Screenshot 2023-10-25 at 11 23 11 AM" src="https://github.com/Satellite-im/Uplink/assets/93608357/4bafc090-8a75-4e3b-8800-41cdce48f814">

**Comment by dariusc93** [comment]
Did this occur while testing on dev on both ends?

**Comment by phillsatellite** [comment]
> Did this occur while testing on dev on both ends?

It has. Ive experienced this with @WanderingHogan and @stavares843 but its not able to be replicated each time. Example I just added Kevin on the released version and his profile picture appeared fine

**Comment by stavares843** [comment]
seems fixed so far
