### ISSUE TITLE
bug(chat): Message is missing when sending attachments 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1403]
**Issue:**
First this problem is not always able to be replicated. I do not have logs or a recording of this happening yet because its been so totally random. It _usually_ happens when you first create an account or chat with someone for the first time 

When user selects images to send in chat and click send nothing will appear in chat until you nav to a different page and then back to the active chat again. Ive seen this on all the OS's so far but like I mentioned above this is totally random and most times not able to be replicated. I wanted to get this ticket started and throughout the day I will keep trying to replicate so I can get a log and a recording of said bug happening. @stavares843 or @tooshel  if you want to keep an eye out for it and also try to get a log or recording of it happening that would be great

**Comment by phillsatellite** [comment]
replicated again today on 11/6/23


https://github.com/Satellite-im/Uplink/assets/93608357/d62a31a2-202f-4191-880c-dc8be1ef7a05

**Comment by stavares843** [comment]
couldn't reproduce

shady

**Comment by phillsatellite** [comment]
This happens mostly when sending .mov

**Comment by tooshel** [comment]
The fix here is a) make the message send before the attachment b) make a better UI for when an upload is in progress. But also we notice that sometimes messages don't go though at all and maybe it's all related? Phill to investigate and update.

**Comment by lgmarchi** [comment]
@phillsatellite is it still happening?

**Comment by stavares843** [comment]
cant reproduce but wasnt always reproducible

**Comment by lgmarchi** [comment]
> cant reproduce but wasnt always reproducible

It is difficult to test, I will do some investigation.

**Comment by dariusc93** [comment]
It looks like its related to the broadcast channel still based on the logs from the video. The way I recall reproducing it was attaching a large file to a message, but since i did increase the channel amount and held the receiver, I wasnt able to reproduce it any longer. 

EDIT: In https://github.com/Satellite-im/Uplink/pull/1457 it increased the channel limits and held the receiver. If this is still applicable then it should be looked into or maybe switch from a broadcast to normal channels

**Comment by phillsatellite** [comment]
Havent been able to replicate this for a while now. Think it should be fine to close and re open if problem appears again
