### ISSUE TITLE
bug(quick profile): the message box opens the chat

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1404]
![image](https://github.com/Satellite-im/Uplink/assets/8636602/2cbbe537-a838-4d16-9724-4abd63386d5e)

click on the box at the bottom of the picture and wait - will be brought to the chats page with that person. I think this should only happen if the enter key is pressed.

**Comment by stavares843** [comment]
@phillsatellite does that happen for you? i don't have that message input field

<img width="755" alt="Captura de ecrã 2023-11-06, às 22 20 06" src="https://github.com/Satellite-im/Uplink/assets/29093946/b75c5881-dddf-41c9-af5f-6f8568ec4637">

**Comment by phillsatellite** [comment]
> @phillsatellite does that happen for you? i don't have that message input field
> 
> <img alt="Captura de ecrã 2023-11-06, às 22 20 06" width="755" src="https://user-images.githubusercontent.com/29093946/280862407-b75c5881-dddf-41c9-af5f-6f8568ec4637.png">

yes we have PR currently open for it

**Comment by phillsatellite** [comment]
Its not going to appear in there since you are already in the chat with Darius, if you start a group chat and view quick profile Message box will appear

**Comment by stavares843** [comment]
ohh thanks 😂
