### ISSUE TITLE
bug(group chats): the icon gets messed up by '+<other members>'

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1407]
![image](https://github.com/Satellite-im/Uplink/assets/8636602/48511808-7966-4e7a-98fd-aacfddb4d1b9)

in this picture, `+4` is obscuring the profile pictures

**Comment by WanderingHogan** [comment]
![Screenshot 2023-11-07 at 9 50 03 AM](https://github.com/Satellite-im/Uplink/assets/2993032/980e1442-278e-42d7-b12d-6d317eff9cc3) @stavares843 @phillsatellite is this still an issue?

**Comment by stavares843** [comment]
i saw this yesterday gonna check again
