### ISSUE TITLE
bug(typing indicator): looks weird in the sidebar. possibly double rendered

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1412]
![image](https://github.com/Satellite-im/Uplink/assets/8636602/55deb127-a778-4873-a89b-8ffd2ffd45d0)

the typing indicator below the chatbar has only 3 dots. in the sidebar it has 6. 

![image](https://github.com/Satellite-im/Uplink/assets/8636602/cb09d279-ea8e-4f1e-9a57-1ae5a72e4c48)

looks like it only happens in group messages
![image](https://github.com/Satellite-im/Uplink/assets/8636602/d8c6a1b6-b1b1-4c9e-91a1-55dddf629583)

**Comment by stavares843** [comment]
still happens
