### ISSUE TITLE
bug(chat): Save file with extension type 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1413]
**Issue:**
When I sent Stu an imagine in chat he was able to download and view it but when he sent it back to me it wouldnt know the picture it was just a blank file thumbnail 

**OS:**
All

**Screenshot:**
<img width="615" alt="Screenshot 2023-10-25 at 4 13 30 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/86df6049-97b5-4eca-9874-30efa5193116">

**Comment by phillsatellite** [comment]
Although for notes: 

Stu sent me a .jpeg/I saved it and sent it back and showed full image as it should

**Comment by Flemmli97** [comment]
what file did you sent at first?
i tested with a .png and when downloading it did it with the file extension despite me not indicating the extension when selecting the folder

**Comment by stavares843** [comment]
works fine here

closing reopen if still happens cc @phillsatellite

**Comment by phillsatellite** [comment]
We replicated with jpeg and png it doesnt always seem to be able to be replicated

**Comment by stavares843** [comment]
thanks @phillsatellite 🔨

**Comment by phillsatellite** [comment]
@stavares843 closing this, tried replicating all morning with multiple file types and each time sent back fine
