### ISSUE TITLE
Icons are shifted out of place 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#142]
**Issue:** In Stu's last PR it shifted the icons a little bit we thought it was best to fix in a new ticket 👍 

**Screenshot:**

<img width="301" alt="Icons3" src="https://user-images.githubusercontent.com/93608357/212959271-8b2fc02b-92a5-49c0-8592-9bb02227024f.png">
<img width="641" alt="Icons2" src="https://user-images.githubusercontent.com/93608357/212959275-32331ff7-b87f-498a-ac26-371f5420a55f.png">
<img width="201" alt="Icons 1" src="https://user-images.githubusercontent.com/93608357/212959276-6ec915ad-61ff-468b-a57b-ede360a69e7d.png">

**Comment by InfamousVague** [comment]
@phillsatellite is this still an issue?
