### ISSUE TITLE
bug(app): app crash during running two instances / emoji install 

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#1436]
Bug: 

I noticed that the app is crashing (sometimes even without having two instances open), due to an the following errors

Log displayed when app crashes:
![image](https://github.com/Satellite-im/Uplink/assets/35935591/0cfb7892-c756-49f6-8cc2-09e821f19060)

Trace Warp Log:
[trace warp log.txt](https://github.com/Satellite-im/Uplink/files/13210078/trace.warp.log.txt)

Steps to reproduce:
1. Build the application
2. Copy last extensions file
3. Open one instance with `cargo run -- --path ../cache/yourfolderone` and another with `cargo run -- --path ../cache/yourfoldertwo`
4. Enter pin and username on both. At some point when you enter to the main screen (chats), one of the instances will crash
5. This issue is happening well on the appium tests for chat, which opens two .exe uplink applications with the path variable to different folders (used to run chats tests) at the same time. One of the instances crashes. Adding this note, to point that I have seen this issue not only when running the app through `cargo run` but also when opening the .exe

Video:
https://github.com/Satellite-im/Uplink/assets/35935591/593fc80c-682d-4f91-b3fe-30b9cc61eac3

Note: This is the same issue that Sheldon faced on last week and we discussed on https://discord.com/channels/997540176488300544/1070507144484507700/1167187444370780231

**Comment by phillsatellite** [comment]
When you have outdated emoji's you will also get this error. On Linux though it happens whenever you try to install emoji's even if they are up to date

**Comment by stavares843** [comment]
we havent see this bug lately so closing

if this happens again we can reopen
