### ISSUE TITLE
bug(drop handler): file drop handler can cause the app to get stuck

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1437]
the app can get stuck like this
![uplink-stuck](https://github.com/Satellite-im/Uplink/assets/8636602/537fcc25-e698-466c-9518-4349c42f3837)

for the above picture, the debug log looks like this: 
![bad-events](https://github.com/Satellite-im/Uplink/assets/8636602/84d0669c-9460-4b27-8cc3-7d4fdf0508a9)

to summarize:
regarding the thing that gets attached to the webview via `with_file_drop_handler`:
- sometimes the event returns an empty list of paths for the hovered event. 
- sometimes the cancelled event is emitted out of order, and sometimes is emitted instead of or before the drop event
- sometimes the hovered event triggers but it isn't followed by a cancel or drop event. 

I suspect this can be blamed on a crappy webview. I think that only handling the drop event would help mitigate the issue because then the app wouldn't have to track the state from "hovered" -> "cancelled" or "hovered" -> "dropped", and thus wouldn't get stuck on "hovering" or fail to drop because the cancel event got inserted between hovered and dropped.

**Comment by tooshel** [comment]
@stavares843 and @phillsatellite to verify if this was fixed with the recent PR

**Comment by stavares843** [comment]
i tried yesterday still happens

**Comment by lgmarchi** [comment]
@stavares843 Is this still happening in all OS?

**Comment by stavares843** [comment]
works fine now
