### ISSUE TITLE
Settings - Toggles glitch a little when switching theme from Dark to Light

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#144]
**Issue:** When switching from Dark theme to Light theme vice versa the toggles will glitch a little 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/212993785-f084d561-e085-4912-8f6b-c64c306e272e.mov

**Comment by WanderingHogan** [comment]
how do you get other themes?

**Comment by tooshel** [comment]
> how do you get other themes?

Settings/General
![image](https://user-images.githubusercontent.com/223338/214154614-5b25081e-daee-4e69-b891-7320380f8d4d.png)

**Comment by phillsatellite** [comment]
@tooshel @WanderingHogan I'm sorry I missed your comment guys, I'm pretty sure that was during my time moving and I might have just overlooked it, so my apologizes, anyways just wanted to comment that I could still replicate this bug on MacOS and WindowsOS on the latest version of Dev

**Comment by InfamousVague** [comment]
It's because the toggles have a animation on their colors, I think it's fine this is as intended. We COULD disable the animations and then re enable them after the theme is applied but I think it'd be a lot of effort for something very minuscule.
