### ISSUE TITLE
Issues from wiring friends to Warp

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#146]
There were some bugs on Stu's PR for wiring Friends to Warp that we wanted to create into a ticket rather than hold up PR 

- [x] When copying the DID sometimes User will face a crash 

<img width="572" alt="Screenshot 2023-01-17 at 4 01 12 PM" src="https://user-images.githubusercontent.com/93608357/213011479-48b12cd7-06ff-40a5-985a-c6406c9035d0.png">

- [x] When User sends a friend request that they have already sent app will crash 

- [x] Sometimes will face a crash when sending the first friend request 

<img width="567" alt="Screenshot 2023-01-17 at 4 02 49 PM" src="https://user-images.githubusercontent.com/93608357/213011750-a16735c7-2606-445c-b8c6-8baabcfdd666.png">

- [x] UI does not update when someone accepts your friend request 

- [x] adding, removing, and blocking friends updates the UI but doesn't trigger the required warp commands

**Comment by sdwoodbury** [comment]
in `ui/src/components/friends/add.rs` i should probably save the user's ID the first time and not make future calls to warp

**Comment by sdwoodbury** [comment]
i believe this is fixed now
