### ISSUE TITLE
bug(chat): Long messages causes user to have to scroll horizontally in chat 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1461]
**Issue:**
When a big message is sent in chat, you are forced to scroll horizontally to view all of it 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/3136a4ac-0d28-40c6-b150-0604bc44da98

**Comment by stavares843** [comment]
still happens
