### ISSUE TITLE
feat(ui/ux): improve ui/ux related to a message reply

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1462]
At this moment is somewhat confusing the UI/UX on the app when replying to a message and needs to be improved.

Do we have a design for this @XileHorizon?

**Comment by XileHorizon** [comment]
I think the replies could be more clarified by adding a profile picture to the message you are replying to, which, especially in groups, will help to distinguish that a message is a reply and who is being responded to.
Before:
![image](https://github.com/Satellite-im/Uplink/assets/33043119/b7363def-e464-4730-8b53-7bb23f144fd2)
After:
![image](https://github.com/Satellite-im/Uplink/assets/33043119/0a38e38a-54b6-41a6-8a86-0f9308fd015f)

Figma Link: https://www.figma.com/file/GrAhLmQWA2kfD1Nw9nd24m/Chats-%2F-Landing-Page?type=design&node-id=881-42499&mode=design&t=HOlZWHqDRotLUNrO-4

**Comment by tooshel** [comment]
The design also has a clear color contrast between the message you are sending and the reply to it . . . should that color change across the app? It looks more like a "light theme" sort of color though.

**Comment by lgmarchi** [comment]
@XileHorizon Messages from my own user now, will be light color in default theme?

**Comment by XileHorizon** [comment]
> @XileHorizon Messages from my own user now, will be light color in default theme?

The coloring used in the mockups is more or less like its own theme (with exaggerated colors to more easily display contrast at a glance), separate from the in-app default theme. I can adjust the colors in the example if that helps, but without Matt's approval, I think we should leave the colors in-app as they are.

**Comment by lgmarchi** [comment]
> > @XileHorizon Messages from my own user now, will be light color in default theme?
> 
> The coloring used in the mockups is more or less like its own theme (with exaggerated colors to more easily display contrast at a glance), separate from the in-app default theme. I can adjust the colors in the example if that helps, but without Matt's approval, I think we should leave the colors in-app as they are.

Thanks my friend, I will work in the other changes so, by the way, I would like if messages from own user would be different.
