### ISSUE TITLE
bug(chat): enter not always works to send a message

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1476]
STR:
- go to chat
- write something
- enter
- sometimes enter does not work

hogan, phil and I noticed this bug

macOS, m1

**Comment by lgmarchi** [comment]
@stavares843 Could you replicate it yet?


It seems dev is working really fine.

**Comment by stavares843** [comment]
so far works good

**Comment by stavares843** [comment]
cc @phillsatellite
