### ISSUE TITLE
task(Chat): Add a progress bar or loading indicator for sending images in chat

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1486]
**Task:**
When you send multiple images in chat, it can sometimes take a while to send. It will send a message bubble immediately without any context and then after about 30 seconds the images will appear. This can leave the user confused and make them try to re-send again and again. We should add a loading indicator or progress bar to clarify that the message is still trying to send 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/435d412e-25ca-4996-a2d0-b12d77eaa015

**Comment by stavares843** [comment]
agree
