### ISSUE TITLE
bug(ui): Dont show markdown style in sidebar 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1489]
**Issue:**
Like title says dont show markdown styles in sidebar, so instead of it showing as **bold** it should show as " * * bold * *"

![image](https://github.com/Satellite-im/Uplink/assets/93608357/9d7cf054-684a-4abe-89cf-d6bd5f7abbc0)

**Comment by sdwoodbury** [comment]
lol https://github.com/Satellite-im/Uplink/issues/946

**Comment by stavares843** [comment]
we know @sdwoodbury but matt asked to remove it so we added a ticket for it to address that
