### ISSUE TITLE
bug(ui): Members render off Call UI when too many members 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1493]
**Issue:**
When you have 10+ users in the group call, the members will start to render off the call UI 

**Screenshot:**
<img width="968" alt="Screenshot 2023-11-09 at 12 17 24 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/afe4ad83-091e-469e-984a-5bb415c15f49">

**Comment by XileHorizon** [comment]
Once it gets to a point where the number of users is going off the screen, it should condense the users past that into a bubble that lists how many users are extra, like so:
![image](https://github.com/Satellite-im/Uplink/assets/33043119/6a4f10ae-849b-480d-8efe-253482f7b437)
To view the additional members not shown, clicking on the condensed user should show a list of the other users: 
![image](https://github.com/Satellite-im/Uplink/assets/33043119/57048667-878b-4f18-ab6b-c9844d431af4)
