### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by MontrealAI** [Satellite-im/Uplink#1504]
What is the LICENSE for Uplink?

**Comment by tooshel** [comment]
Hey! Thanks for pointing that out. We have a license file on our "dev" branch here now:

https://github.com/Satellite-im/Uplink/blob/dev/LICENSE.md

We haven't merged in with main in a really long time. We transitioned to "trunk based development" (vs Git Flow) awhile ago but just haven't made main our default base branch.

**Comment by MontrealAI** [comment]
Thank you.
