### ISSUE TITLE
bug(chat): Message doesnt clear from chatbar when sending code 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1514]
**Issue:**
When you send a line of code and hit the enter key it doesnt seem to be clearing from the chatbar (Ive noticed sometimes it looks like it does clear until the user starts to scroll then code message is back in chatbar & also if you click send rather than hitting enter you can avoid this issue)

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/63cf97c0-cb63-45ee-b5a5-ea8398630921

**Comment by lgmarchi** [comment]
New tests in develop showed us it is working fine, doesn't need this PR anymore.
