### ISSUE TITLE
bug(chat): Scroll to bottom does not appear if only images are sent in chat 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1519]
**Issue:**
Like title says if you start a chat and send enough images to scroll up (without sending any messages with text, then scroll to bottom will not appear 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/7c4fa834-a6a4-4fb5-9dcb-f3208b32e71a

**Comment by Flemmli97** [comment]
might be fixed with #1513

**Comment by sdwoodbury** [comment]
for future reference, to reproduce attach multiple images to a single message rather than sending multiple 1 image messages.
