### ISSUE TITLE
bug(macOS): Click + Drag for chat scrollbar not working

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#152]
**Issue:** Like title says, on Windows you are able to click + drag the scrollbar to move up or down in chat, on MacOS this is not working 

**OS:**
-MacOS
-Linux

**Screen recording:**

https://user-images.githubusercontent.com/93608357/213250064-85561b5c-3007-4c16-9feb-06501dabb50a.mov

**Comment by phillsatellite** [comment]
Re-tested and replicated on latest dev but only on MacOS

**Comment by phillsatellite** [comment]
Still an issue on MacOS, keeping open

**Comment by sdwoodbury** [comment]
likely the same issue as #732

**Comment by phillsatellite** [comment]
Replicated on Dev branch and on PR #732

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Uplink/assets/29093946/bfc8e183-4388-4be4-914b-f462ef78e097

seems fixed, closing 🔨
