### ISSUE TITLE
Context menu on blocked list just shows an X

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#154]
**Issue:** 
- When you right click someone on your blocked list it just shows an X instead of having a context menu 

**Screen recording:** 

https://user-images.githubusercontent.com/93608357/213284098-f269d9f7-8f2e-4764-acf3-8c9d4a3f3c04.mov

**Comment by lgmarchi** [comment]
@phillsatellite It seems this bug was fixed, can you test and confirm please? 

https://user-images.githubusercontent.com/63157656/214320235-557f5213-9691-49e5-a741-541623f7d478.mov
