### ISSUE TITLE
Unable to drag window in mobile

### ISSUE THREAD

**Issue by Jekrimo** [Satellite-im/Uplink#1563]
![image](https://github.com/Satellite-im/Uplink/assets/19398153/83ae7149-cace-44da-8c9c-f77d24484660)
There is a specific div that lives in-between the announcement and buttons that handles the click and drag that gets sized too small, need it to be active everywhere except the actual buttons/announcement link

**Comment by sdwoodbury** [comment]
mobile probably needs an entirely different topbar. that topbar doesn't make sense for a mobile app.

**Comment by Jekrimo** [comment]
> mobile probably needs an entirely different topbar. that topbar doesn't make sense for a mobile app.

I am super down for a mobile topbar. I feel like if we dump the pre-release div it's fine but it is important
