### ISSUE TITLE
task(Groups): Add/removed notification for groups

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1565]
**Tasks**

- [x] **Add/removed notification:** - When a new user is added to the group, or someone leaves the group there should be a notification message sent in chat history saying who was added into the group or who had left the group

- [x] #1633
<img width="226" alt="Screenshot 2023-11-30 at 3 19 27 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/e8f33b9b-d182-4b97-b5e7-acd7a9079890">

**Comment by stavares843** [comment]
same as https://github.com/Satellite-im/Uplink/issues/1114
