### ISSUE TITLE
task(chat): Render markdowns in chatbar 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1567]
**Task:**
- [ ] When clicked into the chatbar typing a message we should try to mimic other applications
here and render the entire text along with formatted markdown to represent the end
result.

**Screenshot:**
<img width="686" alt="Screenshot 2023-11-30 at 3 26 47 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/24f8f549-0a8a-4465-9c2f-80f564fb741b">

**Comment by Flemmli97** [comment]
sounds like duplicate of #1367?

**Comment by sdwoodbury** [comment]
duplicate
