### ISSUE TITLE
feat(friends): be able to search friends

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1578]
let's say I'm friends with 3 of Sheldon's accounts and he FR's me again. I need to find the old Sheldon accounts (for cleanup) and would like to enter "Shel" into a search bar and find all matching friends. 

This would be helpful when finding someone you want to chat with too.

**Comment by dariusc93** [comment]
Might want to note that it might be wise to show the short id in the search along with the username to identify the difference between the user profiles.
