### ISSUE TITLE
bug(chat): Pasting this line of code breaks the UI 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1580]
**Issue:**
When you paste this line of code it breaks the UI (Note that this does not mean all code lines break the UI)

```<div style="width:480px"><iframe allow="fullscreen" frameBorder="0" height="270" src="https://giphy.com/embed/t2UxcutynjwjBVJMi3/video" width="480"></iframe></div>```

<img width="949" alt="Screenshot 2023-12-04 at 5 14 52 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/3788cafc-58ae-4e06-85d4-14af97abd7b1">

**Comment by sdwoodbury** [comment]
fixing this requires an enormous refactor of markdown parsing. It would need to emit a Dioxus element - every markdown thing parsed would need to be transformed to a Dioxus element. 

we always knew that using `dangerous_html` would be problematic. no surprise that something  related to this finally caused a problem.
