### ISSUE TITLE
chore(friends): username only works after users are friends

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1591]
**Issue:**
Adding someone with the username method only seems to work after the 2 users have been friends already. If you try to add 2 fresh accounts the username method will show _No such User found!_ if you try again after using the didkey method friend request will go through fine 

**STR:**
- Copy friends username 
- Send request 
- _Error shows_
- Copy friends didkey 
- Send request 
- Goes through fine 

**OS:**
All

**Comment by dariusc93** [comment]
Just to note that this isnt a bug but instead is intended. Discovery is disabled by default as of https://github.com/Satellite-im/Uplink/pull/1533 for preparation of features to be used later while also cutting back on cpu and network usage. So as a result would require the use of the public keys (or did keys) to send request initially. Once the identities are discovered after sending a request, the corresponding username + short id can be used in the field.
