### ISSUE TITLE
task(groups): Add ability to let other users add friends to the group

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1608]
**Task:**
- [ ] **Ability to let group members add new users to the group:** - Pretty much like the title says, we want to offer the Group Creator a toggle, when toggle is on it allows other members of the group to have the ability to add new users into the GroupChat

**Comment by dariusc93** [comment]
Note: This will require changes over in warp.

**Comment by zeenix** [comment]
> Note: This will require changes over in warp.

The Warp side: https://github.com/Satellite-im/Warp/issues/386

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Uplink/pull/1725
