### ISSUE TITLE
bug(chat): Sometimes images arent sending 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1612]
**Issue:**
Sometimes when a user sends an image it wont send (sometimes restarting the app has fixed this, sometimes it doesnt). When images stop sending any text message you try to send afterwards will not send until image finally does 

This is not always able to be replicated. When I can replicate it again I will get more videos and logs for ticket

**Comment by stavares843** [comment]
also saw the bug here and there not always reproducible

**Comment by dariusc93** [comment]
I might look into this if its still a recurring issue.

**Comment by stavares843** [comment]
yes phil and i noticed this 2 days ago
