### ISSUE TITLE
bug(ui): Issues with Welcome Message 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1623]
**Issue:**

cc: @XileHorizon wanted to see what you thought of these

- [ ] If you right click > hide chat on the active chat you are in, the Welcome message will appear that says "Things are better with friends +Add Someone" The message seems a little odd here since you already have other chats in the sidebar 
![image](https://github.com/Satellite-im/Uplink/assets/93608357/3d659e1e-c4a1-4212-bdb9-292cdc1f6493)

- [ ] If you have friends but no chats started with any of them it will also still say "Things are better with friends +Add Someone" The message seems a little odd here too since you do have friends added, just no chats started with them. Maybe something like "Start a new chat!" Would better fit? 
![image](https://github.com/Satellite-im/Uplink/assets/93608357/0fc37501-a4bc-4bc4-9048-3cd94430f403)
![image](https://github.com/Satellite-im/Uplink/assets/93608357/580b7984-54b4-474b-ace3-3fe4c21645b8)

**Comment by lgmarchi** [comment]
> **Issue:**
> 
> cc: @XileHorizon wanted to see what you thought of these
> 
>     * [ ]  If you right click > hide chat on the active chat you are in, the Welcome message will appear that says "Things are better with friends +Add Someone" The message seems a little odd here since you already have other chats in the sidebar
>       ![image](https://private-user-images.githubusercontent.com/93608357/289964784-3d659e1e-c4a1-4212-bdb9-292cdc1f6493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTQwMDcsIm5iZiI6MTcwMjQ5MzcwNywicGF0aCI6Ii85MzYwODM1Ny8yODk5NjQ3ODQtM2Q2NTllMWUtYzRhMS00MjEyLWJkYjktMjkyY2RjMWY2NDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE4NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYWRkMGMyMzRhNmU2ZDAzODQ1MDFjNmEwMzc1YmM3MTg3OGQ2NTI2MDM1NmJiOTZkZTQxZjQ3ODRmYmFmZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QegK7jponlbTqr93bqTJ5hR1X_1M_Z9U5-wf3VtTK9s)
> 
>     * [ ]  If you have friends but no chats started with any of them it will also still say "Things are better with friends +Add Someone" The message seems a little odd here too since you do have friends added, just no chats started with them. Maybe something like "Start a new chat!" Would better fit?
>       ![image](https://private-user-images.githubusercontent.com/93608357/289965226-0fc37501-a4bc-4bc4-9048-3cd94430f403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTQwMDcsIm5iZiI6MTcwMjQ5MzcwNywicGF0aCI6Ii85MzYwODM1Ny8yODk5NjUyMjYtMGZjMzc1MDEtYTRiYy00YmM0LTkwNDgtM2NkOTQ0MzBmNDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE4NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYzczZWIzMTZlOWVlNjIxOTJmNzRkNzlmYTUzYTdhZmIzMzg0NTkxMzgzODFhNjlhNWIzYjY1ZjQ1M2E4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1gi81PJWh731_DXazweV6STszzXkhs0iDK6TyhkjbLE)
>       ![image](https://private-user-images.githubusercontent.com/93608357/289965251-580b7984-54b4-474b-ace3-3fe4c21645b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTQwMDcsIm5iZiI6MTcwMjQ5MzcwNywicGF0aCI6Ii85MzYwODM1Ny8yODk5NjUyNTEtNTgwYjc5ODQtNTRiNC00NzRiLWFjZTMtM2ZlNGMyMTY0NWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE4NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOTg5MzdkMTA4YmU5NmI0MWVkMjcwNTJjMWNkYmM5OTcyYzk1OGE3M2RkNTZjZjk2NjA2OWQzZWMwMmE2ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJpHK-61-kkMrvGm_bJMTznzlv7RZrjtzm-dz0g1tiI)

I was thinking for the first one, just a message "Life is better with friends, chat with them". 

If you have no friends, we let the way we have now, add someone. 

And the last one I agree with you, "Chat with a friend", and this button will take user to the friends page.

**Comment by XileHorizon** [comment]
Honestly, I think the text "Things are better with friends" is fine on both, it's only the button that needs to change. Maybe it could be "go to friends" and it takes you to your friends list or "start a chat" and a friends list modal could appear(the former would be much simpler).
