### ISSUE TITLE
How to create new account when you forget the pin?

### ISSUE THREAD

**Issue by cseblog** [Satellite-im/Uplink#1646]
Unfortunately I forgot my first pin. Are there any way to create new account?

![Uploading image.png…]()

**Comment by dariusc93** [comment]
Hi! If you wish to erase your current profile, you can remove the `.uplink` directory in your home directory. If you have set path using the path flag, you would remove that directory you have set.

**Comment by stavares843** [comment]
to add on what @dariusc93 mentioned, you can also right click on this icon here 


<img width="494" alt="Captura de ecrã 2023-12-18, às 18 02 02" src="https://github.com/Satellite-im/Uplink/assets/29093946/f8267083-78e6-4eaf-a974-fcb5e3222ee0">


thanks for reaching out, closing this for now feel free to join us on our public [server](https://discord.gg/satellite) in Discord

**Comment by cseblog** [comment]
Than you for very helpful tip.
