### ISSUE TITLE
Unfriend/Blocked buttons stopped working 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#165]
**Issue:** In Friends on All/Pending/Blocked the unfriend and blocked buttons have stopped working. 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/214084071-283cc1b2-6dec-43ca-8d70-4de410c93bff.mov

**Comment by sdwoodbury** [comment]
PR is ready but is blocked by #163
