### ISSUE TITLE
bug(chats): the cats are gone

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#1658]
i pulled dev and built today and after creating a new account got this

![image](https://github.com/Satellite-im/Uplink/assets/8636602/18acfdf8-4eae-4d74-bbea-939aaaf656c8)

**Comment by phillsatellite** [comment]
@sdwoodbury Did you do any extra steps during this flow? I tried with new accounts on Mac/Windows/Linux on latest dev and also the test-release and wasnt able to replicate it

<img width="964" alt="Screenshot 2023-12-22 at 12 33 45 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/6b974688-0e9a-494f-89c6-7eb560909b94">

**Comment by stavares843** [comment]
closing as not reproducible
