### ISSUE TITLE
Friends - Update context menu for incoming friend request 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#180]
**Task:** When we get an incoming friend request, we should be able to right click it to open the context menu and either accept or deny from there as well 

**Screenshot:**

<img width="724" alt="Screenshot 2023-01-24 at 1 00 32 PM" src="https://user-images.githubusercontent.com/93608357/214371789-a10e5df5-cb27-4d4d-b7b1-fcecf99d9581.png">

**Comment by Flemmli97** [comment]
@phillsatellite 
question for this: isnt it kinda redundant to have both buttons on the side for accept/deny and a context menu to do the same thing?
