### ISSUE TITLE
Incoming request count should update automatically 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#186]
**Task:** This ticket is to make sure that across the app anywhere we have a notification badge present related to friend requests we should update them all when the underlying data changes in state.
<img width="958" alt="Screenshot 2023-01-24 at 7 00 05 PM" src="https://user-images.githubusercontent.com/93608357/214447918-3e2c5fa5-a01b-4ba9-be5c-a9132ac8f3a1.png">

**Comment by phillsatellite** [comment]
Through testing on Mac/Windows today my request counter would update each time I received a request even if I had removed a request they had sent before. Gonna close if you are cool with it @InfamousVague

**Comment by dariusc93** [comment]
The counter does update on my side so this could be close as resolve
