### ISSUE TITLE
App icon should include an request indicator 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#187]
**Task:** App icon should include an indicator showing we have incoming friend request(s). This should add to existing global notification count.

**Example:**

<img width="51" alt="Screenshot 2023-01-24 at 7 02 13 PM" src="https://user-images.githubusercontent.com/93608357/214448200-c7a2124c-e4ea-46aa-9c61-30604f9201d5.png">

**Comment by InfamousVague** [comment]
Hogan tackled this in the Notifications utils which are ported over now, so this ticket just needs to implement that and intelligently display notifications in a "combined" view. We may want to use the UI state.

Largely what it'd suggest is going into `ui/src/utils/notifications.rs` and seeing what methods still work (which should be all of them) and wire them up to a state `hook` which watches any actions that drive notification count changes which then calls a `getter` method on state to get the total notification count.

**Comment by phillsatellite** [comment]
Added in Matts PR, going to create any issues with it into a ticket since the scope of this was just to implement it in
