### ISSUE TITLE
UI - When hovering over any text on the app, the cursor should stay the same

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#191]
**Issue:** When we hover our cursor over text within the app, the cursor changes from an arrow to the text cursor. Instead it should remain an arrow no matter what you hover over

**Screen recording:**

https://user-images.githubusercontent.com/93608357/214629727-d068a165-3029-494e-b3b8-fff6071fb034.mov

**Comment by InfamousVague** [comment]
Just a note here we do want the cursor to change when hovering buttons or other things so it's best not to think of this globally, instead we should just be sure to disable text selection on text that is not editable.

**Comment by lgmarchi** [comment]
> Just a note here we do want the cursor to change when hovering buttons or other things so it's best not to think of this globally, instead we should just be sure to disable text selection on text that is not editable.

Question, is normal cursor change even in texts not editable, why are we going to block this? 

Maybe use wants to copy a message from other user, for example. Asking just to understand
