### ISSUE TITLE
Windows OS - User cannot get past Create Username 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#193]
**Issue:** On Windows devices the user is unable to get past the Account Username page. After they type in they're username and they attempt to hit the enter key or click _Create Account_ nothing will happen. No errors will appear in console either

**Notes from Sheldons investigation:**

![image](https://user-images.githubusercontent.com/93608357/214925152-da5ec8cb-1e80-4003-8ca4-0edfc96fe7fd.png)

-but basically in the "create_account.rs" file, it seems like the warp commands are never "matching"  and that's why I get stuck on the screen asking for a username 
-I can see that the tx rx are not "complete" and that it's not timing out or anything

![image](https://user-images.githubusercontent.com/93608357/214925183-23dca904-d890-4ffd-afce-6f9157da3711.png)

**Comment by lgmarchi** [comment]
This issue was solved on PR https://github.com/Satellite-im/Uplink/pull/202
