### ISSUE TITLE
Friends - Add error message when User tries to add themselves or already friends

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#204]
**Task:** If we copy our own did and then try to add ourselves or someone we are already friends with we should have a error message appear. I think for chore I remember us having "You cant add yourself, silly goose" 

https://user-images.githubusercontent.com/93608357/215173715-c68f5f87-1ea3-48ab-af29-1dc5dfaeb157.mov

**Comment by dariusc93** [comment]
Resolved in #357
