### ISSUE TITLE
Settings - Wire up Profile/Banner Pic so its consistent 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#223]
**Task:** Right now when you set a profile picture and you navigate to a different page, when you return your profile picture will reset. 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/216182350-aa8c094e-0d97-431d-a5bb-7415c4ae2f1e.mov

**Comment by sdwoodbury** [comment]
![image](https://user-images.githubusercontent.com/8636602/216454237-95b82b7a-e9ba-4d41-a4e4-6c3e40a0b7e2.png)

**Comment by sdwoodbury** [comment]
this was never implemented to begin with. we probably want to save the image somewhere, such as in the `.uplink` folder.

**Comment by sdwoodbury** [comment]
done as of https://github.com/Satellite-im/Uplink/pull/378
