### ISSUE TITLE
Settings - Wire up "Compress & Download Cache"

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#227]
**Task:** Like Title says we want to wire up Compress and Download Cache in Settings/Developer. We should include a notification when User clicks button

**Screenshot:**
<img width="952" alt="Screenshot 2023-02-01 at 6 26 52 PM" src="https://user-images.githubusercontent.com/93608357/216190590-ff0d1c37-4725-430e-b142-d6cc519d49ec.png">

**Comment by sdwoodbury** [comment]
waiting for some other pr's to go in. done (minus a progress indicator) in `feat/export-cache`
