### ISSUE TITLE
Friends - Copy ID sometimes not working 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#229]
**Issue:** Mostly on linux when you try to copy your DID it won't work

**OS:**
Linux

**STR:**
1. Go to friends tab 
2. Try to copy DID

**Screen recording:**

https://user-images.githubusercontent.com/93608357/216211123-16dc5814-ea08-42bb-a35d-b9e8d95bc3a0.mov

This is it working right after I stopped recording, sometimes bug is able to be replicate sometimes its not 

https://user-images.githubusercontent.com/93608357/216211192-af6f04c8-5062-4a55-9e3a-50e59f5aaf4b.mov

**Comment by WanderingHogan** [comment]
I can't get this to work no matter what I do

**Comment by phillsatellite** [comment]
> I can't get this to work no matter what I do

hmm I honestly haven't had that many issues with this at all today when I think about it. Maybe tomorrow we can debug together and see if we can find anything shady and see if I can replicate it some more

**Comment by dariusc93** [comment]
> I can't get this to work no matter what I do

Havent been able to get it working on linux while on mac it should work. Unsure about windows.
