### ISSUE TITLE
Chat - When no messages are sent yet, have a messages starter appear in the sidebar

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#232]
**Task:** In Chore when you would start a chat and not send any messages yet, in the sidebar under the User it would say like "No messages sent yet, send one!" I think we should add something similar into Uplink 

**Screenshot:**
<img width="959" alt="Screenshot 2023-02-02 at 2 20 21 PM" src="https://user-images.githubusercontent.com/93608357/216429246-bda76549-2b41-49b5-b10d-9e66e94f2de8.png">

**Comment by sdwoodbury** [comment]
this got merged in, but I was wondering if it would look even better if instead a message was displayed in the Compose view.
