### ISSUE TITLE
Settings - Wire up ability to save Username and Status

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#235]
**Task:** This ticket is to start the process for adding the ability to save username and status and have it persist when you change pages or leave the app and come back 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/216432615-783413d0-804e-40ff-86fe-4b6b87512bda.mov

**Comment by sdwoodbury** [comment]
completed in https://github.com/Satellite-im/Uplink/pull/378
