### ISSUE TITLE
Chat - Add New Message indicator that we had in Core 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#237]
**Task:** In Core we had a indicator in chat when a user would send a new message in chat and after the User would view the message the indicator would disappear. 

**Screenshot:**

![image](https://user-images.githubusercontent.com/93608357/222226939-3e701587-4ec1-40e9-a07b-0e38051db43f.png)

**Comment by sdwoodbury** [comment]
it looks like we have this as of 2023-03-08
![image](https://user-images.githubusercontent.com/8636602/223824739-4475a26a-38f1-4ddd-a6c7-3ea086736ee4.png)

**Comment by phillsatellite** [comment]
Fixed but have a few issues with it on MacOS and Windows created ticket here https://github.com/Satellite-im/Uplink/issues/408
