### ISSUE TITLE
Chat - Add Quick Profile feature that we had in Core 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#238]
**Task:** We want to add the same Quick Profile concept that we had in Core. While you were in chat, if you clicked the other users avatar a quick profile would pop up with the option to message the user. If the user clicked they're own 

**Screenshot:**
<img width="467" alt="Quick Profile " src="https://user-images.githubusercontent.com/93608357/216454673-7b886550-42c1-403b-99c0-de36dbc2a3a4.png">

https://user-images.githubusercontent.com/93608357/216454688-1ddec673-6941-4bd0-9687-a29b4d067f12.mov

**Comment by XileHorizon** [comment]
I've provided examples of a right-click menu for quick messaging users. One contains a chat bar in the menu for messaging on the fly. whereas the other is more simple and only has a button to navigate quickly to the chat.
With chat bar:
![image](https://user-images.githubusercontent.com/33043119/218824775-d5c2cf2f-b590-49cb-afe0-1e7a77f6f526.png)
![image](https://user-images.githubusercontent.com/33043119/218824821-bf75c377-a48c-4b90-867b-1547b4d60e83.png)

Without chat bar:
![image](https://user-images.githubusercontent.com/33043119/218825693-946868c2-1973-4def-bd27-90ae2d3f3353.png)
![image](https://user-images.githubusercontent.com/33043119/218825729-13d2f5c6-1fdb-4e6e-b079-06059dfa1240.png)

(Note: The message button isn't entirely useful in this context but would be more useful in communities. it could be left out when right-clicking on the chat page.)

**Comment by sdwoodbury** [comment]
friends layout: 
![image](https://user-images.githubusercontent.com/8636602/230493794-0237112f-6b22-44ef-8387-62b495a2d122.png)

chats layout:
![image](https://user-images.githubusercontent.com/8636602/230493879-bda6d567-4792-415e-b249-c204c901089e.png)


I'm not sure how different these menus should be. I'm not saying they should be exactly the same but maybe the friends context menu was overlooked. 

It might be useful to have the "chat" option on the compose layout. If in a group chat, that option would let you switch to a direct conversation with a participant. 

Personally I don't like the way the new menu looks. But if one of the CSS wizards can move things around later then I'm ok with it for now.
