### ISSUE TITLE
UI - Sidebar/Nav bar is missing when logging in 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#265]
**Issue:** On Windows OS when you log in, it will load in as the mobile layout but be the side of the Desktop Window. This will persist through the rest of the app as well. I recall @luisecm and @WanderingHogan having this issue on MacOS before as well but I still could not replicate that.

**OS:**
Windows

**STR:**
1.Log in on a Windows machine 

**Screen recording**

https://user-images.githubusercontent.com/93608357/217152973-8e1c278b-e1dc-4e65-9b0b-b7bb02fa17d1.mp4

![image](https://user-images.githubusercontent.com/93608357/217068537-7c6b5412-ef2c-441d-85c8-13fd132662cc.png)

**Comment by sdwoodbury** [comment]
i noticed this too. i believe it's because of the resize event 
![image](https://user-images.githubusercontent.com/8636602/217352069-df0abafd-a7f5-4f83-8f78-f7c69208396e.png)

@InfamousVague

**Comment by sdwoodbury** [comment]
![image](https://user-images.githubusercontent.com/8636602/217360538-7f12bff3-cbd3-4fef-9ee6-5688a3cd754a.png)
