### ISSUE TITLE
Global - 404 in README.md

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#286]
STR:
- go to https://github.com/Satellite-im/Uplink
- scroll down
- [CONTRIBUTING.md](https://github.com/Satellite-im/Uplink/blob/dev/CONTRIBUTING.md). returns 404

<img width="1014" alt="Captura de ecrã 2023-02-10, às 16 35 28" src="https://user-images.githubusercontent.com/29093946/218145698-7fdd32ad-954f-4bc4-9fec-1305daeebc1f.png">

**Comment by tooshel** [comment]
Thanks Sara! I also saw a pr where we are adding a file about contributing to docs/contributing.md and it might be better to put that at the root since that's more common.

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Uplink/pull/274/files#diff-008e085d9d1d048f67e77da4c6c5ac2cb02d4c5957c991d39c04f43172052469
