### ISSUE TITLE
UI - Bugged at a fix size on start

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/Uplink#302]
When creating a new account or logging in with the window at a fix size, the UI would show the sidebar, but not show "Add Someone", however, if I were to maximize the UI and return it back to its correct size, it would show the button but not the sidebar. Clicking the button would would being me to the friends page and the sidebar would show, but the UI would remain off.

![image](https://user-images.githubusercontent.com/3918024/218882150-fb61d2f0-ba31-4270-9e19-97512a430112.png)

![image](https://user-images.githubusercontent.com/3918024/218882165-882699c7-3c93-42fe-b6fc-28aae140a404.png)

![image](https://user-images.githubusercontent.com/3918024/218882179-aa0333be-b6cc-47b2-bc28-d2b232bdfd4c.png)

![image](https://user-images.githubusercontent.com/3918024/218882190-72a2921a-1071-4f88-b5ce-6893fc051c15.png)

![image](https://user-images.githubusercontent.com/3918024/218882561-2e422e89-091a-455a-af3b-72fef0d993ba.png)

![image](https://user-images.githubusercontent.com/3918024/218882575-cc7e1a7e-ef47-4244-90d7-0ab9b84e193c.png)

Tested on i3 on linux 

Note: It attempts to use mobile view it seems but still sits between desktop and mobile when starting at that size.

**Comment by phillsatellite** [comment]
I think this is the same issue created here https://github.com/Satellite-im/Uplink/issues/265 for Windows we could add to either or

**Comment by dariusc93** [comment]
Hmm it might be related. Hard to say though since normal size it shows everything fine.
