### ISSUE TITLE
Friends - Clear DID after  a request is sent

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#304]
**Issue:** After a User sends a friend request the friends DID should clear from the input box.

**OS:**
Windows 
MacOS

**STR:**
1. Send friend request 
2. After sent DID will still remain in input box

**Screen recording:**

https://user-images.githubusercontent.com/93608357/219258695-4097bf5b-c374-4274-833d-c6445b629d4a.mov

**Comment by dariusc93** [comment]
Resolved in #314
