### ISSUE TITLE
Global - Changes requested from Matts PR #274

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/Uplink#318]
i recommend moving this and the use_future to the end of this function. the function was laid out so the `use_future`s were declared after `main_element`, which allowed a dev to see the end result of this function without having to scroll past all the `use_future`s

_Originally posted by @sdwoodbury in https://github.com/Satellite-im/Uplink/pull/274#discussion_r1113615666_

**Comment by dariusc93** [comment]
Resolved in https://github.com/Satellite-im/Uplink/pull/325
