### ISSUE TITLE
Global - Changes requested from Matts PR #274

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/Uplink#319]
the `expect()` call has an incorrect error message. `read_dir` doesn't fail when the directory is empty, but when the directory can't be read. 

ideally this wouldn't panic either.

_Originally posted by @sdwoodbury in https://github.com/Satellite-im/Uplink/pull/274#discussion_r1113609801_

**Comment by dariusc93** [comment]
Resolved in https://github.com/Satellite-im/Uplink/pull/325
