### ISSUE TITLE
Crash -  failed to read debug.log: No such file or directory

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#327]
**Issue:** Got a crash in Settings/Dev with the logger 

`2023-02-22 11:26:22 | DEBUG | Developer settings page rendered.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ui/src/logger/mod.rs:150:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ui/src/logger/mod.rs:150:18`

**OS:**
-Windows
-Mac

**Steps to reproduce**
-make a new account 
-go to settings/dev
-turn on dev mode 
-turn on Save logs in files 
-click desktop view

**Screen recording:**

https://user-images.githubusercontent.com/93608357/220691315-7849cbcc-4404-49a9-9265-80fd69426893.mov

**Comment by sdwoodbury** [comment]
the culprit was `unwrap`. i may have been responsible for that. the bug will be fixed soon.
