### ISSUE TITLE
bug(macOS): User is forced to double click after getting a notification

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#351]
**Issue:** Sometimes it seems on MacOS the user will be forced to double click to navigate throughout the app. So far we think this is mostly a MacOS problem (maybe it has to do with Safari window?) 

**OS:**
-MacOS

**Screen recording:**

https://user-images.githubusercontent.com/93608357/221954099-406aea69-f3f6-4a17-a37a-f7198e2f0f67.mov

**Comment by phillsatellite** [comment]
Replicated on May 2, 2023 on a m1 Macbook Pro

**Comment by stavares843** [comment]
seems no longer happens
