### ISSUE TITLE
Notification - Alerts will appear as NOT YET IMPL sent a request 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#352]
**Issue:** When you get an incoming friend request, it will appear as "NOT YET IMPL sent a request" but this doesnt happen all the time in screenshot you can see Sheldons request sent through and appeared fine 

**Screenshot:**
![Screenshot_2023-02-28_at_12 01 47_PM](https://user-images.githubusercontent.com/93608357/221954988-94734f43-7dfd-42ca-b568-aa27d125f586.png)

**Comment by dariusc93** [comment]
Should be a easy change to add the name or did key of the identity. 

Ref https://github.com/Satellite-im/Uplink/blob/687401ec2edf4601ff7286074a20c61fde16675f/common/src/state/mod.rs#L912
