### ISSUE TITLE
Chat - User has to scroll to see latest message they sent

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#353]
**Issue:** When the user is sending messages in chat, you will sometimes have to scroll to the bottom of the chat to see the latest sent message. On Windows this can happen pretty much every message but on MacOS this is able to be replicate about every other message 

**OS:**
-Windows 
-Sometimes Mac

**Screen recording:**

https://user-images.githubusercontent.com/93608357/221960501-2506490d-1455-469a-80ee-0ff9b47ca866.mov

**Comment by dariusc93** [comment]
This happens on Linux as well where one has to scroll down to see new messages.
