### ISSUE TITLE
Global - Logo PNG missing if you do cargo build instead of run

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#366]
**Issue:** Like the title says, if you do cargo build to open the app instead of doing cargo run the welcome PNG will be missing on the landing page

**STR:**
Run cargo build 
Open the Uplink app
PNG will be missing 

**Screenshot:**

![image](https://user-images.githubusercontent.com/93608357/222523514-898bcb34-d9de-48ee-ac18-6ae6c4580c09.png)

**Comment by tooshel** [comment]
It seems like dioxus is recommending we take the images and make them part of the install process. Right now I was able to use the new "dioxus build" command to generate an MSI and soon I'll be able to bundle assets (like images) with that installer.

**Comment by tooshel** [comment]
This is related to how we build the apps and Stuart is looking into that now. It's not just the images that are missing . . . fonts are missing too. All of those assets are being referenced in the code with links relative to the root of the uplink project and we need to copy those files and folders over to wherever uplink is installed.
