### ISSUE TITLE
task(global): Investigate loading times when restarting Uplink

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#410]
**task:** Sheldon, Hogan and I have been doing testing on Uplink Dev branch tonight. We have found some things that are interesting: 

When one of your friends updates they're profile picture and you close and re open the app, the chat and friends page will take very very long to load. During that time you will get a error in chat for each friend that you have that says "Copy <did> found in sidebar but not in hashmap" 

After about 1-3 minutes your friends page will load, the user who changes their pfp, will have a blank profile picture for about another 30 seconds after the list has loaded. Once it updates the pfp they changed all your chats and _most_ messages will load again 

![image](https://user-images.githubusercontent.com/93608357/223578544-65d0bfa5-02c2-462e-8023-523c47511522.png)

**Comment by dariusc93** [comment]
Do note that there is usually a difference in performance between debug and release (since release does alot of optimizations in itself), however there may be more room for optimization in uplink.

**Comment by tooshel** [comment]
@phillsatellite Can we just close this one? I haven't seen this issue in a long time.

**Comment by tooshel** [comment]
Phill agreed this was solved!
