### ISSUE TITLE
Settings - Font size for Default is smaller than the font size for other themes 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#416]
**Task:** Matt has.a fix for this in his latest PR. The font size is bigger for all the other themes compared to Default 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/223835231-fa00599b-0182-4cab-a5d3-471bc6b9a4fd.mov

**Comment by InfamousVague** [comment]
This should be resolved in the extensions branch.
