### ISSUE TITLE
Settings - Add option to clear Profile pic + Banner

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#423]
**Task: ** From Stu's list, we want to add the ability for a user to clear they're PFP and PFB from the Settings/Profile page

**Comment by sdwoodbury** [comment]
This feature doesn't work on Linux as of yesterday when PR #436 was merged. It's a UI issue at this point.

**Comment by phillsatellite** [comment]
Verified its fixed on my end after merging #448 tested this on Windows 11 Linux(Ubuntu) MacOS
