### ISSUE TITLE
Global - Investigate wether changing your name causes the status icon to no longer be green

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#425]
**Task:** There is a possability that changing your name will cause your online status indicator to no longer be green. This ticket is to investigate and jot down whatever notes we have from our findings

**Comment by phillsatellite** [comment]
Some notes from what I found when testing:

- It does appear like when User A changes their name, online indicator will change from Green to Grey only on User A's side. On other partiess side User A will appear with a green status indicator with name changed 

https://user-images.githubusercontent.com/93608357/223881993-10d441ce-f809-4c69-abfc-59e12a9d353c.mov

- Second thing is, it seems like when you first login your friend will appear offline (until after 60 seconds then it realizes) but if your friend sends you a message before that 60 seconds their indicator will change from offline to green immediately

https://user-images.githubusercontent.com/93608357/223881572-a2605438-fed4-4e24-aeca-a1b1991b9c28.mov

**Comment by dariusc93** [comment]
A recent PR will refresh friends every 60 seconds. Receiving a message likely rerendered the page to show the status change hence why the second one is the way it was. 

For the first one, that is client side in uplink. Likely not grabbing or updating status after the name change. Does it still show offline when you send something?

**Comment by sdwoodbury** [comment]
This is now fixed.
