### ISSUE TITLE
Mock - Running existing mock crashes

### ISSUE THREAD

**Issue by Flemmli97** [Satellite-im/Uplink#427]
When running the app with mock data for the second (or more) time crashes the app with a 
```
thread 'main' panicked at 'assertion failed: state.friends().initialized', ui/src/main.rs:374:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I guess this is due to a recent change of #398 in `friend.rs` causing the `initialized` to not serialize properly

**Comment by sdwoodbury** [comment]
I believe this is fixed now .
