### ISSUE TITLE
UI - Login page should display username

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#439]
**Issue:** When User is logging back into the app, the PIN page display's _WELCOME BACK, UNKNOWN_ instead of displaying the Users name 

**STR**
- Create an account 
- Log out/back in

**Screenshot:**
<img width="562" alt="Screenshot 2023-03-10 at 10 18 52 PM" src="https://user-images.githubusercontent.com/93608357/224462446-fd9a4c4b-97a3-4972-b0f1-802907c2bd0a.png">

**Comment by InfamousVague** [comment]
We should create a flags.json or some other file to house this, it should also house the last theme chosen.
