### ISSUE TITLE
Global - Panic when closing out app 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#441]
**Issue:** I've been getting a panic whenever I close the app with the X button at the top corner. The App icon will remain in the dock as if the app is still running. If you close from within the Terminal all is good. 

**Panic:**
**MacOS & Linux**
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /Users/phillwisniewski/.cargo/git/checkouts/dioxus-1e619ce595d3799d/d521da1/packages/core/src/scheduler/task.rs:78:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Windows**
thread 'notify-rs windows loop' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }',

**OS:**
-MacOS
-Linux (Ubuntu)
-Windows
(The. error for Windows was a little different. I figured this was because the difference in OS and was still related to the same problem, if its not related I'll create a separate ticket)

**Screen recording:**

https://user-images.githubusercontent.com/93608357/224462908-748ffe10-e278-45d3-8954-420230ccd5da.mov

**Comment by dariusc93** [comment]
I have been seeing this for awhile but seem to be at random for me (maybe due to how my window manager on linux is), but we may have to catch the event so we can close things more gracefully, at least in the UI. So far, under testing, it doesnt seem to affect anything but may have implications in the future depending on what is sent via channels.

**Comment by ealmloff** [comment]
The Windows error seems like it is from [hot reloading](https://dioxuslabs.com/docs/0.3/guide/en/getting_started/hot_reload.html) which should be disabled on release builds

For Linux and MacOS https://github.com/DioxusLabs/dioxus/pull/881 should fix this issue
