### ISSUE TITLE
Global - Name change not working 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#444]
**Issue:** Seems something had broke name changing over the weekend, User A changes their name but will never update on User B's side 

**OS:**
-Windows
-MacOS

**STR**
-Change Username 
-On User B's side wait at least 60+ seconds

**Comment by dariusc93** [comment]
Can you try again with the latest merge?

**Comment by dariusc93** [comment]
Just as a note: I did quickly test and it does work. Havent tested prior to #430 being merged though
