### ISSUE TITLE
Files - Drag & drop not working on Linux

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#452]
**Issue:** Was replicated on Linux Ubuntu, with the latest dev branch I wasnt able to get drag/drop files to work

**Screen recording:**

https://user-images.githubusercontent.com/93608357/224859836-474e9f4c-d97b-4c8c-ad02-099ae92fabca.mov

**Comment by dariusc93** [comment]
It works fine for me on linux, but what I can assume is that youre using wayland in your DE and that may not be playing well. If you do `echo $XDG_SESSION_TYPE` in terminal, does it come back as `X11` or `wayland`?
