### ISSUE TITLE
Chat - Add indication that messages are or are not encrypted.

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/Uplink#46]
They will be encrypted in 99% of cases but we should port over the message at the top of message history that says "Messages are secured by end-to-end Encryption and sent over a peer-to-peer network"

**Comment by phillsatellite** [comment]
@InfamousVague do we still want to have this at the top of chat?

**Comment by dariusc93** [comment]
Note that in warp, messages are stored and sent encrypted.
