### ISSUE TITLE
Settings - Welcome message missing 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#471]
**Issue:** When creating a new account when you go to Settings/Profile there should be a welcome message with the mascot. It looks like it went missing 

**OS:**
-MacOS
-Windows
-Linux

**Screen recording:**

https://user-images.githubusercontent.com/93608357/225948292-101d2b45-cf26-48e0-91ca-57cecd8644d3.mov

**Comment by InfamousVague** [comment]
Bumping priority since this is a regression.
