### ISSUE TITLE
Chat - Messages are loaded without scrolling

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/Uplink#477]
We do not want to over render things in the DOM. Currently messages load in groups but it will continue to load even if you're not scrolling (it will load chunks of messages and the scrollbar will get smaller without any interaction such as as scrolling to the top.

**Comment by sdwoodbury** [comment]
i thought the lazier-loading PR fixed this. https://github.com/Satellite-im/Uplink/pull/467

**Comment by InfamousVague** [comment]
We can have QA check it out later. I haven't tested since last week
