### ISSUE TITLE
Friends - UI is rendered offscreen when friend has Status chars maxed out

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#490]
**Issue:**
-When you add a friend that has a status that reaches the 128 char max, half the UI will be rendered off-screen 

**OS:**
-MacOS
-Windows
-Linux

**STR:**
- Add a friend
- Make sure that friend has a status with 128chars 
- Navigate to _Friends_ page

**Screenshot:**

<img width="987" alt="Screenshot 2023-03-21 at 6 31 43 PM" src="https://user-images.githubusercontent.com/93608357/226757018-0eab9fb4-6723-4caa-8899-d2ff0ceb4bc2.png">

**Comment by stavares843** [comment]
💥
