### ISSUE TITLE
bug(chat): Allow autofocus on input for sending messages/replies with/without files attached 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#494]
**Issue:** When you attach a file to a blank message in chat and try to use the enter key to send, it will not send and user is forced to click the send button 

on MacOS and Windows when you select a file from the file browser hitting enter after will not do anything. But if you drag and drop the files in the Enter key works fine 

edit: I retested and user is not auto focused onto the input when replying without an attachment as well

**OS:**
-Linux
-MacOS
-Windows

**STR:**
1. Start a chat
2. Attach a file to message 
3. Try to send by hitting the _Enter key_

**Comment by dariusc93** [comment]
I recall this affecting other platforms too since internally it checks to see if there is an attachment or not to determine how it will be sent.

**Comment by Flemmli97** [comment]
note: seems to be an windows issue

**Comment by phillsatellite** [comment]
replicated as of April 20th on MacOS and Windows 

https://user-images.githubusercontent.com/93608357/233498950-ebec8d4a-fd26-40b6-9463-c63acb33f26f.mov

**Comment by phillsatellite** [comment]
Replicated 05/01/23

**Comment by Flemmli97** [comment]
cannot replicate it on my end. tested systems:
linux (pop os 22.04)
macos (monterey 12.6.4)
windows (windows 10)

**Comment by stavares843** [comment]
no longer happens
