### ISSUE TITLE
Chat - highlight/clicking message will open file uploader 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#505]
**Issue:** Within chat, if you highlight the text of one of the messages and then click it a couple times it will open the File uploader and say "0 files to upload!" when this happens there is no way to exit except for closing down the client 

error in console - 

```
[0323/161707.060:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
error: process didn't exit successfully: target\release\ui.exe (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```

**OS:**
-Windows

**STR:**
1. Start chat 
2. Send messages 
3. Highlight text within a message
4. Click a lot 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/227344330-2e1bf9d9-4c91-40d2-ae14-4695cd54ef0f.mp4

**Comment by lgmarchi** [comment]
I and @phillsatellite have tested, we were not able to replicate it anymore, we are going to do more tests during the day, if not be possible to replicate, we are going to close this ticket
