### ISSUE TITLE
Change Status Indicator Icon

### ISSUE THREAD

**Issue by XileHorizon** [Satellite-im/Uplink#51]
**Description:** Change the current status indicator icon for desktop from the current "ComputerDesktop" icon to the "Circle" icon.

**Requirements:**

- [ ] Circle should be solid.
- [ ] Change should be made to desktop only.

**Assets:**
Now included in the DioxusHeroicons is a Circle icon for use in this purpose.

| View      | Resource |
| ----------- | ----------- |
| Current      | <img width="153" alt="image" src="https://user-images.githubusercontent.com/33043119/210406900-7929b2a0-7dc2-4ed4-8932-236cdac5518b.png">       |
| Mock-up   | <img width="127" alt="image" src="https://user-images.githubusercontent.com/33043119/210406996-38ff213f-a630-49fa-9427-40f520f3dad2.png">        |

**Figma Mock:**
https://www.figma.com/file/GrAhLmQWA2kfD1Nw9nd24m/Chats-%2F-Landing-Page?node-id=265%3A11907&t=XKyDBJXtrVI98cpn-4

**Comment by dariusc93** [comment]
Resolved in #59
