### ISSUE TITLE
UI - Create chat button goes missing 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#510]
**Issue:** When you are able to start scrolling in the sidebar from the amount of friends you have, the start chat button will go missing 

**OS:**
Mac
Windows
Linux

**Screen recording:**

https://user-images.githubusercontent.com/93608357/227574499-d7d804c4-8e53-4569-bccb-b1938bbe4f90.mov

**Comment by lgmarchi** [comment]
It was merged into Group Chat branch. 

https://github.com/Satellite-im/Uplink/pull/515
