### ISSUE TITLE
UI - Improve UI for creating new group chat

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#511]
**Task:** Not sure if we have UI planned for this yet, but this ticket is for improving the UI for when the User is creating a new chat 

**Screenshot:**

<img width="951" alt="Screenshot 2023-03-24 at 11 44 19 AM" src="https://user-images.githubusercontent.com/93608357/227575054-406b81be-4fc5-4f63-845d-58b2e00bdb29.png">

**Comment by lgmarchi** [comment]
Closing this Issue. @InfamousVague did a PR to fix it. https://github.com/Satellite-im/Uplink/pull/547
