### ISSUE TITLE
add ability to submit bug report

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#521]
needs a ui to do the following:
- attach a screenshot and description 
- attach a crash report

needs an API to send the report to

**Comment by InfamousVague** [comment]
one thing we need to be very careful of here is to not expose any important personal information (or personal information about the users account at all, really) when capturing the reports. This will make things a lot safer while we're still pre code audit as well.

**Comment by sdwoodbury** [comment]
sounds like we could have a link to an [upvoty](https://www.upvoty.com/) page where users could provide feedback
