### ISSUE TITLE
Chat - Autofocus not working after selecting emoji/attachment 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#537]
**Issue:** When you are typing, if you select an emoji or put in an attachment you cannot continue typing until you click back into the input box 

**OS:**
windows

**Screen recording:**

https://user-images.githubusercontent.com/93608357/228028104-250bc169-724d-40df-8a4a-d54835789c2c.mov

**Comment by Flemmli97** [comment]
note: seems to be an windows issue
