### ISSUE TITLE
Groups - add ability to leave a group and add more users 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#545]
**Task:** The user should be able to leave the group chat, using the context menu or having a button to leave maybe have some thing in the title bar. 

We also want to be able to add more people to the group 

**Screenshot:**
<img width="941" alt="Screenshot 2023-03-28 at 4 02 04 PM" src="https://user-images.githubusercontent.com/93608357/228353712-7ace6e73-2ee7-4ddb-9969-ac050398deaa.png">

**Comment by dariusc93** [comment]
Using `RayGun::add_recipient` and `RayGun::remove_recipient` would allow the creator of said group chat to add or remove members of that group. A user who leaves (eg delete the group conversation via `RayGun::delete`) would make the user "leave" the group.

**Comment by lgmarchi** [comment]
This issue will be on 3 PRs: 
- Remove group and leave it 
- Remove someone from the group as admin
- Add someone to the group after group been created

**Comment by lgmarchi** [comment]
PR opened to delete or leave group, and delete chats as well. 
https://github.com/Satellite-im/Uplink/compare/leave-group-chat?expand=1
