### ISSUE TITLE
Chat - Add loading component to messages 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#561]
**Task:** 

**WAITING ON #560 **

We need a loading indicator to let our Users know they warp is communicating and trying to send the message 

Indicator needs designed 

- [ ] Indicator should appear next to the any message attempted to be sent 
- [ ] Indicator should persist until Warp has successfully delivered the message to the recipient

**Comment by dariusc93** [comment]
For p2p (or direct messaging), using `RayGun::message_status` should work fine in letting one know if a message has been sent or not. A message that isnt sent would generally be in the queue.

Do note that this isnt exactly applicable for group chat at this time, but would change in the near future.
