### ISSUE TITLE
Friends - Add loading component to Friends 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#567]
**Task:**

**WAITING ON #560  **

There are a few places in friends that we want to add a loading component to indicate that Warp is working and just taking a little while 

- [ ] After sending a request sometimes in Outgoing it will show only the did of the user you are trying to add. We should instead display the loading component in Outgoing until warp has successfully delivered the request to the recipient and it is able to display all of the correct information in the Outgoing requests. 

- [ ] We need to also display it after clicking _Accept_ request. Sometimes after clicking accept request warp will be loading and you can continue to accept the request. Behavior should be - Loading indicator appears after clicking _Accept Request_ and should persist until Warp has successfully added that person to your friends list and you are able to chat with them

**Comment by dariusc93** [comment]
The problem mostly is that the UI doesnt retry to fetch the identity in regards to outgoing request, which would only show a portion of the did until there is a form of an update (warp doesnt emit events for any discovered identities, though I could enable the flag for it, which *should* help). See #464 and #501. 

I think it would be appropriate to have a loading indicator *only* if its actually attempting to check at a set interval, to fallback to showing the partial did identity after so many times with it checking in the background (eg checking every 15 seconds). Showing the indicator but with no actual attempts would cause confusion as it did in the previous uplink when identities that werent resolved would be showing a loading indicator and unable to close or close the request (same with incoming in which one wasnt able to reject or block a request).
