### ISSUE TITLE
UI - Call buttons are clickable and visible on debug 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#579]
**Issue:** The call and video buttons should not be clickable right now and should be greyed out. If you run in --release mode it is appears correctly. If you run in debug the buttons are visible and clickable 

**OS**
Mac 
Windows 

**Screenshot:**

--Release 

<img width="318" alt="Screenshot 2023-04-03 at 1 42 04 PM" src="https://user-images.githubusercontent.com/93608357/229586344-ae622a99-9fd9-4d5b-ae81-1f65460eb5e8.png">

Debug 

<img width="384" alt="Screenshot 2023-04-03 at 1 43 16 PM" src="https://user-images.githubusercontent.com/93608357/229586555-331cad6c-93fa-4448-bdbc-45e51dc0df3b.png">

**Comment by sdwoodbury** [comment]
these were left enabled in debug mode on purpose. but if the desired behavior is different then go ahead and change it
