### ISSUE TITLE
Groups - Typing indicator will persist (even when user is clicked outside of app)

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#583]
**Issue:** In a group chat with User A,B, and C if User C sends a message and then clicks out of the app the typing indicator will persist for an extremely long time. Usually up to 5-6 minutes after the user sends the message 

**OS:**
-Linux
-MacOS
-Windows

**Screen recording:**

https://user-images.githubusercontent.com/93608357/229623052-433f8130-b29a-48dd-8fd4-448b55f51459.mov

**Comment by dariusc93** [comment]
I've noticed this recently but couldnt pin down the commit that may have caused it, but it may have happened after changes related to last week discussion. It does persist, but seem to eventually timeout or stop. 

Note: I seen this happen on direct messaging 

EDIT: After some testing, it may be related to upstream. That should (hopefully) be fixed sometime this week when a patch version release and I could revert my workaround.
