### ISSUE TITLE
UI - Chats Input Bar - No error message displayed when user has reached the max number of chars

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#591]
- After typing 1024 characters, user does not get any error message mentioning that maximum number of chars has been reached

Screenshot:
![image](https://user-images.githubusercontent.com/35935591/230162169-c5d656f0-94a3-490b-8044-cd7b37b8c0ad.png)

**Comment by dariusc93** [comment]
@luisecm The max is 2048 in uplink unless it was recently changed
