### ISSUE TITLE
UI - PNG and THEMES are missing when building with --release

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#596]
**Issue:** When you build with --release the PNG kitties and Themes will be missing. I assume we most likely just moved the assets with .uplink

**Screen recording:**

https://user-images.githubusercontent.com/93608357/230182122-1913d661-a45c-4515-9504-31af1dae19d8.mov

**Comment by dariusc93** [comment]
Related to 7fd44c9b6688b64e4d3f2c17965bc5bd502bf877 . Adding `DEBUG` env var will allow them to load under release. 

cc @sdwoodbury

**Comment by sdwoodbury** [comment]
fixed
