### ISSUE TITLE
component(async-loading): Modify Input to create loading state

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Uplink#617]
![Screenshot 2023-04-10 at 11 28 33 AM](https://user-images.githubusercontent.com/2993032/230957003-1d0e5835-7ad7-4a7d-8c76-ffa7a3589616.png)

We need the input to have an optional parameter for loading. 

The default would be false, if it was true, there needs to be a spinner on the right side input, and inputting new characters needs to be disabled. If there are other things decorating the input, like this back button, it needs to be temporarily removed, and the loader shown there. While in the loading state, it should still show the value in the text input while disabled.

Above is an example in settings where, when you click out of changing your username, we should see a loading icon appear.

**Comment by tooshel** [comment]
Found another way to solve this. Thanks stu!
