### ISSUE TITLE
task(ui): Improve file attachment UI by adding a loading indicator

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#631]
**Task:**

- When sending a file, we should display a progress bar under the input bar representing each file that is being uploaded. (put progress bar with name on the bottom left under the bar and the progress percent / elapsed time on the right under the bar) We should move the preview of the file to above the chatbar like discord and other apps do. This isn't loading stuff but this is something we should (doesn't have to be you) work on. I can help with styling this. I just am worried i'll hit a bunch of issues trying to get the functionality, though it should be quite simple.

**Screenshot:**
<img width="838" alt="Screenshot 2023-04-11 at 6 09 48 PM" src="https://user-images.githubusercontent.com/93608357/231299615-206f2eac-7715-4548-a81a-fe35f0a293e2.png">

**Comment by Flemmli97** [comment]
linking to keep track of it:
[https://github.com/Satellite-im/Warp/issues/246](https://github.com/Satellite-im/Warp/issues/246)

**Comment by stavares843** [comment]
still valid
