### ISSUE TITLE
bug(ui):When downsizing the font scale, the prerelease/issues report overlaps with Maximize button

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#644]
I found this issue on MacOS:

If you downsize the font scale to less than 1, then the prerelease indicator overlaps with the maximize button

![image](https://user-images.githubusercontent.com/35935591/231845905-2eae576b-836e-4bf1-b7b9-d6e9f3d45828.png)

Hogan's suggestion: When you scale the font . . . don't override the padding on the left.

**Comment by stavares843** [comment]
still happens

**Comment by phillsatellite** [comment]
Latest dev on MacOS seems to be a little bit better but still renders behind window controls just a little bit 

<img width="395" alt="Screenshot 2023-06-05 at 7 24 21 AM" src="https://github.com/Satellite-im/Uplink/assets/93608357/000f9e41-1dc5-4d63-9b3d-3cdb71bba928">

**Comment by stavares843** [comment]
no longer happens
