### ISSUE TITLE
bug(ui): Messages arent sending with correct format when entering new lines

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#673]
**Issue:**
If you have a message like:
Look at this 

New Message 

It will appear in chat after sent like:
Look at this 
New Message 

It will be missing the new line that was entered when typing 

**OS:**
All

**Screen recording:**

https://user-images.githubusercontent.com/93608357/232878669-f7ea658a-7bc1-4288-ac9f-6a0bbf1e1c72.mov

**Comment by tooshel** [comment]
A fix was found but it broke markdown . . . . so this is ongoing.
