### ISSUE TITLE
task(ui): Add loading indicator when user is trying to preview file 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#683]
**Task:**
We want to include a loading indicator for when the user clicks to preview a file in the Files panel. Right now if they continue to click while warp is loading than they will open multiple tabs 

**OS**
All

**Screen recording:**

https://user-images.githubusercontent.com/93608357/233194627-2ced247e-1492-4aa7-8095-d685cf0abf68.mov

**Comment by lgmarchi** [comment]
> **Task:** We want to include a loading indicator for when the user clicks to preview a file in the Files panel. Right now if they continue to click while warp is loading than they will open multiple tabs
> 
> **OS** All
> 
> **Screen recording:**
> 
>  Screen.Recording.2023-04-19.at.4.35.22.PM.mov

Bug problem to open a lot of file preview of same file is solved in new PR opened, but Loading component not added yet. 
https://github.com/Satellite-im/Uplink/pull/735

**Comment by tooshel** [comment]
Went a different way to solve this but as far as we know it's not a problem anymore. Closing!
