### ISSUE TITLE
task(notifications): Clicking banner alert should navigate user to said chat

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#694]
**Task:**
When you are clicked out of focus of the app and you receive a new message/get the banner alert in the top right of the screen, you should be able to click that alert and have it take you to said chat 

**OS:**
All

**Screenshot:**

<img width="429" alt="Screenshot 2023-04-20 at 3 18 03 PM" src="https://user-images.githubusercontent.com/93608357/233466513-d09201ba-21d9-486b-aecc-738770f3d28a.png">

**Comment by sdwoodbury** [comment]
I found some stuff that might help with windows
https://github.com/microsoft/windows-rs
https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast
https://learn.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification?view=winrt-22621
