### ISSUE TITLE
UI - Blocked Users status appears as REQUESTED NOW 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#698]
**Issue:** 
Like the title says, when you block a user their status will change to REQUESTED NOW

**OS:**
All

**STR:**
Block a user

**Screenshot:**
<img width="648" alt="Screenshot 2023-04-20 at 8 42 05 PM" src="https://user-images.githubusercontent.com/93608357/233514878-e0be3595-275c-47d2-886d-d9bd3b56bcac.png">

**Comment by dariusc93** [comment]
Looks to be related to https://github.com/Satellite-im/Uplink/blob/c0be35f16b3a8ca450f5daa0fe94afcd25c5d375/ui/src/components/friends/friend/mod.rs#L84-L89 though thats just from glancing over the code and not testing to be sure
