### ISSUE TITLE
bug(windowsOS): Missing emoji's

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#699]
**Issue:**
-On Windows OS there are a few emoji's missing within the menu 

**OS:**
-Windows 

**STR:**
-Open and scroll through the emoji's menu 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/233515655-ac955fda-0b83-4967-a461-d440aea8100f.mp4

**Comment by tooshel** [comment]
What's the expect fix on this one? Like, should we limit the emoji set on windows to only ones they can see? Or limit the set of all emojis to just ones that are universal?

**Comment by tooshel** [comment]
I think the consensus was to just hide the emojis that don't show up on windows. @Jekrimo  . . . you also mentioned that it was random which ones were not showing up. Did you resolve that?

**Comment by Jekrimo** [comment]
I did resolve that! I was unawares of some stuff I had to do for the extension

**Comment by tooshel** [comment]
@Jekrimo this seems to be an issue . . . are you working on this one?

**Comment by tooshel** [comment]
The original idea with this was to hide emojis we were not using. After trying that and failing, we decided we needed to dig in more and found that we can use the Noto font on windows.  Just going to close this out and get a fresh start on a new ticket!
