### ISSUE TITLE
component(logout): Add logout button in settings

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#756]
As discussed with @WanderingHogan we don't currently have a logout button to logout in the app.

This ticket is to add that.

We could add it in settings, in one of the tabs for example.

**Comment by Jekrimo** [comment]
What do you guys think about putting it here? 
@stavares843 @WanderingHogan 
![image](https://user-images.githubusercontent.com/19398153/235511354-41563703-777f-4a7c-8650-63040bac342b.png)

**Comment by stavares843** [comment]
sounds good by me 🔨

**Comment by tooshel** [comment]
seems strange to put that on top of the banner image . . . even just a button under status might be better?

**Comment by Jekrimo** [comment]
agreed on the banner, maybe right under the banner or what if we float it in the bottom right corner?

**Comment by tooshel** [comment]
yeah, if you could get it under the banner, floating on the right, without messing with rest that could be good. But now I'm wondering what that "color" selector does. Maybe that goes and a logout replaces it! Or the color moves down to be on the same line as status and logout can be lined up with username but way on the right.

**Comment by tooshel** [comment]
Note that "logout" just has the effect of closing the app and then opening it again . . . just takes you back to the enter pin screen. Is that right?

**Comment by stavares843** [comment]
also agree in the banner thing

i though logout was really to ditch the session

**Comment by Jekrimo** [comment]
unsure about the function of logout just yet, but yeah I think we all agree on placement at least!

**Comment by tooshel** [comment]
"ditch the session" is the same as just closing the app. You open the app and you need to enter a pin. Instead of a button you could add a message saying "close the app to log out" since it's the same net effect. 

In settings/developer we have "clear cache" which also takes you back to the enter pin screen but in that case all your friends and conversations are gone too!

**Comment by Jekrimo** [comment]
kinda like this?
<img width="942" alt="Screenshot 2023-05-04 at 11 08 56 AM" src="https://user-images.githubusercontent.com/19398153/236276567-aecafd0e-c98b-4f21-be03-96b25bacdc33.png">

**Comment by tooshel** [comment]
unfortunate that it had to add all that extra space and make that page feel different from all the others

**Comment by Jekrimo** [comment]
yup, agreed. now. what if, we put it under the 'about' in the scroll there?

<img width="942" alt="Screenshot 2023-05-04 at 11 08 56 AM" src="https://user-images.githubusercontent.com/19398153/236279088-0d9445e5-ef6e-4254-8e04-658129db57e6.png">

**Comment by tooshel** [comment]
That could work too though that list is already really long.

**Comment by dariusc93** [comment]
To quickly notate on this: The clean way might be to close/reopen the app, but to get around that, dropping the warp runner and restarting that while going back to the pin screen should also be enough to "logout", though any task or streams being held would also need to be cleaned up and dropped too.

**Comment by Jekrimo** [comment]
@dariusc93 do you know of an example of `dropping the warp runner and restarting`? I was looking for a simple rust snippet to simply close and reopen and couldn't find it, but I would think ensuring we kill all warp tasks is a good idea if the simple restart won't work

**Comment by dariusc93** [comment]
@Jekrimo I havent tested it in uplink but dropping `WarpRunner` in `main.rs` should be enough, but may require some additional changes to signal to the state about this too. @sdwoodbury should be able to provide more insight on this.

**Comment by Jekrimo** [comment]
sweet deal sounds good. State should be easy from what I am seeing but of course am prob wrong

**Comment by Jekrimo** [comment]
Update on logout. Works but we have this bug where the file picker stays open forever and the weird second window that persists

But, it does log out
<img width="1196" alt="Screenshot 2023-05-09 at 3 30 20 PM" src="https://github.com/Satellite-im/Uplink/assets/19398153/99c5b95c-a449-483e-8c58-f3a274de8c93">

**Comment by Jekrimo** [comment]
@sdwoodbury I think you mentioned having the crash logger being able to be turned off? Is it something we could add into dev settings to be able to turn off and on and maybe that fixes our issue? Can you direct me to the location the crash logger is being called and I'll try and figure it out if you don't have any red flags going off?

**Comment by sdwoodbury** [comment]
@Jekrimo dev no longer uses folder picker on crash. That change was merged in today.

**Comment by Jekrimo** [comment]
Baller, We still got this panic that is blocking it from relaunch I think

<img width="1000" alt="Screenshot 2023-05-15 at 11 19 09 AM" src="https://github.com/Satellite-im/Uplink/assets/19398153/d2d17834-4572-4890-be4d-02a7ae15929e">

**Comment by tooshel** [comment]
Could we just redefine what logout is to something like . . . open a dialog that says "Click okay to close Uplink. Launch the app again to log back in." and leave it at that?

**Comment by stavares843** [comment]
any news on this? 🔨

**Comment by tooshel** [comment]
This was more complicated than we thought and closing the app has the same effect so closing this for now.
