### ISSUE TITLE
bug(ui): incorrect update prompt

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#764]
after installing release 0.0.1, the app still tells me that an update is available.  Deleting the `~/.uplink` folder and starting fresh didn't help. 

![image](https://user-images.githubusercontent.com/8636602/235680918-10f96dba-2a67-46f0-bc14-32fdaf631a24.png)

**Comment by tooshel** [comment]
Maybe we can combine this with a ticket to add the "current version" somewhere in the app. Right now I have no way of knowing if that screenshot is running the latest release.

**Comment by tooshel** [comment]
I think this is because the cargo.toml has 0.1.3 and it will never match the 0.0.1 from the tag. The fix for this is to package up the apps again and make sure those match.

**Comment by tooshel** [comment]
Stuart said we can close this since we don't need to change anything for the next release for this to go away.
