### ISSUE TITLE
bug(files): Folder will save as "un-named directory" 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#775]
**OS:**
-Windows
-Linux
-MacOS

**Issue:**
-A user is able to save a folder with no name and it will appear with the name "un-named directory" 

**STR:**
-Go to Files / Create a folder
-Type some text into the input box 
-Backspace all your text
-Save folder

**Screenshot/recording:**

<img width="87" alt="Screenshot 2023-05-02 at 9 22 26 PM" src="https://user-images.githubusercontent.com/93608357/235817553-43568eba-5f5f-422c-b993-69d0aa8df752.png">

https://user-images.githubusercontent.com/93608357/235817570-36b82183-88cf-4d8f-a0be-0566154c833b.mov

**Comment by dariusc93** [comment]
This isnt really a bug as by default it would `un-named directory` if a name isnt set. In uplink, it should probably not create a directory if a name isnt entered in, though it would not allow a directory to be created under the same name in the same level.
