### ISSUE TITLE
component(files): Implement file storage amount

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#780]
**OS:**
-All

**Task:**
-In the top of files it displays amount of storage used in Files. Right now it is not implemented so it says 0mb/10mb. We want to display how much the user has used

**Screenshot:**

![image](https://user-images.githubusercontent.com/93608357/236280655-a7930a93-f17c-4377-9b75-286e87b6ec8e.png)

**Comment by dariusc93** [comment]
The best way to calculate what a user has used would be grab the root directory by calling `Constellation::root_directory` and then to use `Directory::size` , which would iterate over the items and calculate its sum.
