### ISSUE TITLE
chore(project): reorganize ui project 

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#794]
The `ui` project has the following layout
![image](https://user-images.githubusercontent.com/8636602/236901820-9f3773c4-1547-45e5-958e-d13c12fd808c.png)

if you want to look at what the chat view (for example) view does, you would go to `layouts/chat.rs` to get the top level file. But when you want to dig deeper and look in a submodule, you now have to go to `components/chat/` and look around. Normally, one folder would contain all the views, each view would have its own folder, and the top level Element would be in the `mod.rs` file. 

I think the project would be better organized if `layouts` was replaced with a folder called `views`. 
Back to the chats example, there would be a `views/chats` folder, `layouts/chat.rs` would be moved to `views/chats/mod.rs` , and everything else from `components/chat` would go in the `views/chats/` folder.

**Comment by lgmarchi** [comment]
@sdwoodbury We were talking about it. My suggestion for app, is to organize is as clean arch, I think it would not take so much time, and it is a pattern between other languages as well. Here is a image how Clean Arch works. 
<img width="724" alt="image" src="https://github.com/Satellite-im/Uplink/assets/63157656/02e782af-ddd5-47a8-a9ff-96210f931263">

It follows a flow like this: 

<img width="485" alt="image" src="https://github.com/Satellite-im/Uplink/assets/63157656/294350e6-56a0-4eba-a0fe-b517512cbc2a">

It is an arch similar we used in our flutter uplink project: 
https://github.com/Satellite-im/Uplink-Mobile/tree/dev/lib

**Comment by lgmarchi** [comment]
@dariusc93 I will work with this issue as well, to organize files and code in UI

**Comment by stavares843** [comment]
this PR was closed

https://github.com/Satellite-im/Uplink/pull/911

does it mean we no longer need this ticket btw?
