### ISSUE TITLE
Account Creation - User can set an emoji as a Username 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#80]
**Issue:** When User is creating a Username in Account Creation and they make it a single emoji `🥸 ` the input field turns green as if its a accepted Username and when they try to proceed the app will crash

**Screenshot/screen recording**

<img width="859" alt="Screenshot 2023-01-06 at 12 35 53 PM" src="https://user-images.githubusercontent.com/93608357/211069867-3d36269b-9cb6-40a8-b212-b60d8e150d52.png">

https://user-images.githubusercontent.com/93608357/211069903-e06de593-9bfd-41cd-a54e-9696547e451c.mov

**Comment by dariusc93** [comment]
If its using warp to check, this may be due to the fact that the length of the username is less than 4 characters and not specifically that its an emoji (though the emoji part should be filtered out in the UI).

**Comment by dariusc93** [comment]
~~Also a side note, this looks to be apart of #77, which havent been merged in yet.~~ Nevermind looks like the ticket was written due to a discussion there. Either way, the previous message above would still stand
