### ISSUE TITLE
Bug(startup): Missing dll on Windows 10

### ISSUE THREAD

**Issue by XileHorizon** [Satellite-im/Uplink#812]
Some Windows 10 machines may be missing the VCRUNTIME140_1.dll, which is required for the app to start. This has been tested on two different Windows 10 machines on update 22H2.

Workaround is to install the latest Visual C++ Redistributable from Microsoft found here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by tooshel** [comment]
I looked into this a bit and there is probably a permanent solution though it's going to take a bit of digging. Maybe we can look into this next week @XileHorizon? 

https://github.com/rust-lang/rust/issues/100874

**Comment by WanderingHogan** [comment]
closing in lieu of Stu's ticket, but will link this ticket there for more info
