### ISSUE TITLE
chore(installer): bundle windows dependencies in installer

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#818]
see this guide: https://wixtoolset.org/docs/v3/bundle/ 
and this example: https://wixtoolset.org/docs/v3/howtos/redistributables_and_install_checks/install_dotnet/

I believe that at lest the C++ runtime needs to be bundled with the windows installer. 

Something similar may need to be done for Mac. Need to test on a non-dev machine as developer machines already have all the needed dependencies installed.

**Comment by WanderingHogan** [comment]
Linking Kevin's original ticket just in case https://github.com/Satellite-im/Uplink/issues/812

**Comment by dariusc93** [comment]
Is this still ongoing?

CC @sdwoodbury

**Comment by tooshel** [comment]
@dariusc93  This one only is an issue on a brand new windows 10 machine. A few of us have looked into it but it will require some complicated WIX magic and personally I as just hoping the dioxus tools (or something like Tauri) would take care of this for us. We can for sure unassigned it from stu. This isn't high priority.
