### ISSUE TITLE
bug(resize): if you start the app in a bigger size, doesn't resize properly

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#821]
STR:
- cargo run
- maximize app
- enter app
- appears like this

macOS, m1

https://github.com/Satellite-im/Uplink/assets/29093946/f9ffcd9c-fe1d-4eda-8161-6d3a546998fc

**Comment by phillsatellite** [comment]
Replicated on June 5th on Windows and MacOS. This issue doesn't seem to happen on Linux
