### ISSUE TITLE
bug(toast): toast is hidden

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#822]
STR:
- cargo run
- chat
- hover last icon
- toast is hidden

<img width="1108" alt="Captura de ecrã 2023-05-16, às 12 11 16" src="https://github.com/Satellite-im/Uplink/assets/29093946/8353accc-c40f-48f7-a07b-56c321d09cb5">

macOS, m1

**Comment by phillsatellite** [comment]
Was not able to replicate on any OS with latest dev

**Comment by tooshel** [comment]
> Was not able to replicate on any OS with latest dev

I tried on Mac and Windows in group chats and regular chats and the "Coming Soon" hover was never cut off.
