### ISSUE TITLE
bug(crash): app crash's in preview image in files

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#825]
app crash's when you click the preview

STR:
- go to files
- add any image
- click
- crash's

macOS, m1

https://gist.github.com/stavares843/15a9ef2d52fdc36b56fda931e3219a20

https://github.com/Satellite-im/Uplink/assets/29093946/779be07f-cd12-43c0-9088-2e589b8dd55c

**Comment by dariusc93** [comment]
@stavares843 although the UI needs to be wired up to properly display the image after the recent PR, could you confirm if this is still an issue with dev currently?

**Comment by stavares843** [comment]
gonna check 🔨

**Comment by stavares843** [comment]
still happens 🔨

**Comment by tooshel** [comment]
@stavares843  aybe you should add that you have an old version of safari and old version of the OS?

**Comment by stavares843** [comment]
safari 15, macOS 12 😂

**Comment by stavares843** [comment]
will close considering the crash isn't reproducible in prod and is also not reproducible in dev in other mac's on our team
