### ISSUE TITLE
chore(improvement): Chat remains favorited 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#835]
**Issue:**
When you favorite a chat and then hide it, if you create a new chat then click the favorited avatar it will open the old chat that was hidden.

Hogan was thinking about doing "delete chat" instead I think that might work 

**OS:**
All 

**STR:**
Start chat with User A
Favorite chat
Hide chat 
Start new chat with User A
Click User A in favorites 

**Screenshot:**

https://github.com/Satellite-im/Uplink/assets/93608357/e4b0e8d7-3ea6-42df-8c19-4f344c2df62e

**Comment by tooshel** [comment]
Closing this in favor of a new ticket where we update the UI when you are in a group to make it more clear you are in a group.
