### ISSUE TITLE
chore(groups): need UI update for Group Chats

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Uplink#851]
Group chats can have a single person or multiple people.

Here is what a group chat looks like for multiple (3) people:
![image](https://github.com/Satellite-im/Uplink/assets/2993032/a9582ea5-2b24-4e58-8534-ecc4718d3de0)

Here is a group with 1 other person (the default group name will be the username unless you manually type something like i did here):
![image](https://github.com/Satellite-im/Uplink/assets/2993032/d196d5a1-d92b-4b86-8101-ee41eee0e72f)

Here is a DM:
![image](https://github.com/Satellite-im/Uplink/assets/2993032/fdf035ed-4bd6-4fe4-95f4-16fe33774dfe)

We need to make it easier to distinguish when you are in a group, and when you are in a DM, which is especially an issue when you are in a group that is just two people.

**Comment by WanderingHogan** [comment]
iOS Group from Phil:
![image](https://github.com/Satellite-im/Uplink/assets/2993032/fe611a6c-5919-42a0-9750-1d77d9a4ca85)

Telegram group:
![image](https://github.com/Satellite-im/Uplink/assets/2993032/5f2c89f8-7cec-41c9-b753-e8a1a61f249a)

Discord Group:
![image](https://github.com/Satellite-im/Uplink/assets/2993032/4bdb0478-2db5-4da4-9626-39cf2bc4a353)

**Comment by XileHorizon** [comment]
**Profile display:**
- In Direct Messages, show only the profile picture bubble of the person you are communicating with. (It currently works like this)
- Groups should always show multiple profile pictures(how it appears in the sidebar now, but not in the topbar yet):
      - Display two profile picture bubbles for a group with only two members.
      - If a group has more than three members, display three profile picture bubbles and a "+count" to represent additional members.

**Status line:**
- For groups, display "Members (count)" to indicate the number of group members.
- For Direct Messages, "status of other member"

**In Direct Messages:**
- Remove the feature that shows two participants search in a dropdown when clicking on the status bar. Instead, could you provide a shortcut to the user's profile?

**In the Group search dropdown:**
- Introduce an option for users to remove other members from the group. [directly from the search list]
- Add an empty slot at the end of the list with the label "Add User" to allow for the addition of new group members.
- Make the user clickable to show their profile

Could you fix the cursor when you hover over the clickable area? It should display a pointer to clearly indicate the area is interactive.

**Comment by WanderingHogan** [comment]
I think multiple tickets:

Create Public User Profile Page
- [ ] Create a Profile Page (not the edit page, but what other people can see)

Group Page Updates (ticket #887 )
- [x] Make Image in Header of Groups match the sidebar (currently it looks like it is removing your own pfp)
- [x] Where a status message would be for a user, show the "Members (#)"
- [x] When you click this whole area, show the members dropdown like usual
- [x] Fix the count in the members dropdown to include yourself

Modify edit group/members dropdown to be the same component in groups (ticket #893 893)
- [ ] Buttons on right side to remove them
- [ ] At end of list, button to add more users to list 'Add User'
- [ ] Make user clickable to show profile

Direct Message Page (blocked by first ticket)
- [ ] Click on user to see profile

**Comment by WanderingHogan** [comment]
gonna break them into tickets and then close this one
