### ISSUE TITLE
chore(arch): new arch for rust app

### ISSUE THREAD

**Issue by lgmarchi** [Satellite-im/Uplink#858]
About new arch for the app, ideia is to have files organized like this example: 

<img width="188" alt="image" src="https://github.com/Satellite-im/Uplink/assets/63157656/0d57ad54-1239-4cad-aea5-29b819402c12">

<img width="183" alt="image" src="https://github.com/Satellite-im/Uplink/assets/63157656/6cee0696-0dc1-444b-9a86-e251f81a3025">

**Comment by dariusc93** [comment]
Could you explain a bit more on the feature modules in the application?  Is this related to the what is being rendered on the application?

**Comment by lgmarchi** [comment]
> Could you explain a bit more on the feature modules in the application? Is this related to the what is being rendered on the application?

No @dariusc93 , it is about separate layers, apply SOLID and Clean Arch, apply clean code rules 

Because app is become bigger and more complex, so it is good to start have a decoupled layers and single responsibilities, to not become a problem for us and new developers in the future. 

I commented new arch in development channel, any question, you can dm me

**Comment by lgmarchi** [comment]
We have decided to not follow with new arch!
