### ISSUE TITLE
feat(Groups): Add ability to be able to rename group after already created 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#863]
**Issue:**
When a group is already created, the user should be able to edit the name of it 

**Screenshot:**

<img width="964" alt="Screenshot 2023-06-06 at 11 05 43 AM" src="https://github.com/Satellite-im/Uplink/assets/93608357/fb2e2be9-bcbe-4f10-9963-af140679b5eb">

**Comment by Flemmli97** [comment]
it seems this is already a thing though. clicking on edit group -> you can change the group name there
