### ISSUE TITLE
bug(chat): icon closing the modal is very small

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#872]
STR:
- go to chat
- send message
- right click
- reply to message
- the close icon is very small

<img width="643" alt="Captura de ecrã 2023-06-09, às 19 13 00" src="https://github.com/Satellite-im/Uplink/assets/29093946/77e77208-ee2f-423f-88c9-a8c6c025f6ff">

macOS, m1

**Comment by lgmarchi** [comment]
We already had this problem, if I remember is just an CSS config, I am getting this ticket
