### ISSUE TITLE
chore(chats): reactions position

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#874]
STR:
- go to chat
- send message
- right click

suggestion - when we add a reaction goes below the message but the reaction list is above the message, shouldn't both be either both in top or both in below?

<img width="304" alt="Captura de ecrã 2023-06-09, às 19 14 32" src="https://github.com/Satellite-im/Uplink/assets/29093946/0c996ccc-d367-49da-b5ef-06f95f808d4f">
<img width="285" alt="Captura de ecrã 2023-06-09, às 19 14 38" src="https://github.com/Satellite-im/Uplink/assets/29093946/7d91db3f-c650-421a-a95b-a9764cfa67ca">

macOS, m1

**Comment by lgmarchi** [comment]
@stavares843 For me it is not a problem. 

@XileHorizon Can you give your UX opinion here, please?

**Comment by XileHorizon** [comment]
I think we should eventually use the emoji picker for the reactions or at least have options be in the context menu when you right click rather than be an additional action. Maybe we have a list of common reaction emoji and an extra button to view them all?

**Comment by lgmarchi** [comment]
> I think we should eventually use the emoji picker for the reactions or at least have options be in the context menu when you right click rather than be an additional action. Maybe we have a list of common reaction emoji and an extra button to view them all?

I think both can work. But your second alternative would be better, if we are using Uplink in Mobile, then thinking in the future, I vote for second alternative, and click like in plus button and open emoji picker.
