### ISSUE TITLE
chore(settings): toggle takes lot of time to update

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#877]
STR:
- go to settings
- after you activate and try to deactivate this toggle takes a lot of time, around 10s

<img width="655" alt="Captura de ecrã 2023-06-09, às 19 22 27" src="https://github.com/Satellite-im/Uplink/assets/29093946/ac7444b8-5c2a-4c2d-b747-7b9c846de3c1">

macOS, m1

**Comment by Flemmli97** [comment]
tested on linux: not affected

**Comment by Flemmli97** [comment]
could also not reproduce on my mac air

**Comment by Flemmli97** [comment]
retested again. on an m2 mac. couldnt reproduce
