### ISSUE TITLE
chore(chat): when user has no avatar just appears a white ball

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#881]
STR:

- settings
- themes
- lunar eclipse theme
- chat
- when users have no avatar just appears a white ball 

<img width="446" alt="Captura de ecrã 2023-06-09, às 19 35 39" src="https://github.com/Satellite-im/Uplink/assets/29093946/6aa6fdae-6e5c-426c-8dea-af1beba7fcb9">

macOS, m1

**Comment by lgmarchi** [comment]
Use this crate to generate random profile pictures 

https://github.com/paritytech/polkadot-identicon-rust
