### ISSUE TITLE
bug(chat): Any spaces on new lines will not appear when sent

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#888]
**Issue:**
When you start a new line of text, if you put any spaces in the start of the line they will now show up in chat 

**OS:**
All

**Screenshot**
![image](https://github.com/Satellite-im/Uplink/assets/93608357/c2af157d-1408-4bb3-ba4e-b8e2cc0d2c57)

**Comment by Flemmli97** [comment]
~~should we keep the spaces? as i think they are deliberately removed. e.g. discord does the same thing were leading and trailing whitespaces get removed~~

nvm i see what you mean now
