### ISSUE TITLE
bug(groups): remove a user and adding it again will crash the app

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#897]
Note: This issue is not always reproducible

Steps:

1. Create a group chat with another participant
2. Go to Edit Group and Remove the other user
3. Then, try to add back the same user
4. The app will crash

Happening on MacOS
https://github.com/Satellite-im/Uplink/assets/35935591/13222efb-7964-4d9e-be29-baf332f853c1

**Comment by stavares843** [comment]
also reproducible here 🔨

**Comment by stavares843** [comment]
crash log
https://gist.github.com/stavares843/0edacfb4b58589b25c5959e9b466ef36

**Comment by tooshel** [comment]
@phillsatellite and @stavares843 both have confirmed this issue is happening . . . are you looking into it @Flemmli97

**Comment by phillsatellite** [comment]
This used to happen every so often, but this seems to be able to be replicated each time now

**Comment by stavares843** [comment]
phil and i tested various times no longer crash's so far


if it happens again we can reopen the ticket
