### ISSUE TITLE
improvement(sidebar): sidebar search should separate matching results from username and group chats

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink#926]
1. Go to Sidebar Search
2. Type any characters that should match only a result in the sidebar search
3. Multiple results are returned in sidebar even when these do not match with the search string (looking for "C" and getting results such as "Our Group" that do not contain a group name matching the search string, but contain usernames matching with search string

Update: As discussed during meeting today, we will display sidebar search results matching with the search string for usernames and also group names including a username matching with search string
We will have more details on the UI/UX for it soon. Changing the title of this as it is not a bug but just an improvement to the sidebar search

https://github.com/Satellite-im/Uplink/assets/35935591/da90cf9b-1f4e-492a-b9a9-0b6829d81f0e

**Comment by lgmarchi** [comment]
@luisecm I think it is a little bit weird, because search bar is looking for users inside group as well, and not group name.

What do you think?

**Comment by Flemmli97** [comment]
potentially when fixing this issue we can make the search also not case sensitive. (or this might be good in another issue)

**Comment by luisecm** [comment]
Adding @XileHorizon to the loop, so we can get more clarification on how should we display the results separated for usernames and groups. 

@Flemmli97 I just gave a try to the search bar and does not seem to be case sensitive for me when looking for usernames, only when looking for group users:

![image](https://github.com/Satellite-im/Uplink/assets/35935591/1c45a8ef-2585-4d47-8506-76f8659dad9d)

@lgmarchi  I can update the ticket name to reflect better whats expected to do here, thanks for bringing it up!

**Comment by lgmarchi** [comment]
> Adding @XileHorizon to the loop, so we can get more clarification on how should we display the results separated for usernames and groups.
> 
> @Flemmli97 I just gave a try to the search bar and does not seem to be case sensitive for me when looking for usernames, only when looking for group users:
> 
> ![image](https://user-images.githubusercontent.com/35935591/247673404-1c45a8ef-2585-4d47-8506-76f8659dad9d.png)
> 
> @lgmarchi I can update the ticket name to reflect better whats expected to do here, thanks for bringing it up!

I think it would be better UI/UX, because it is not a bug, but a improvement that we need to do. Thanks for it @luisecm.

**Comment by lgmarchi** [comment]
> potentially when fixing this issue we can make the search also not case sensitive. (or this might be good in another issue)

I already did it in previous PR my friend, thanks for that point.

**Comment by lgmarchi** [comment]
![image](https://github.com/Satellite-im/Uplink/assets/63157656/6d3c2e1e-04e2-4ddb-8a27-3948d1af4538)
