### ISSUE TITLE
User gets stuck on Account Creation

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#93]
**Issue:** Lucas and I noticed this bug this morning, User tries to create an account when they do `cargo run -- --mock`but they get stuck on the Username and Password page. If they do just `cargo run` it will load fine but no mock data will appear.

**Screen recording:**

When User tries `cargo run -- --mock`
https://user-images.githubusercontent.com/93608357/211353681-8ec92bd3-2a85-44c2-8528-05ee798cb73a.mov

When User does `cargo run`

https://user-images.githubusercontent.com/93608357/211374305-afe74cb1-0888-4424-8953-9ff61c1b0e6a.mov

**Comment by dariusc93** [comment]
@phillsatellite Could you confirm if this is still an issue?

**Comment by phillsatellite** [comment]
Issue is fixed 👍  thought this was linked and closed automatically my fault!
