### ISSUE TITLE
bug(global): Investigate why Uplink is slow without release flag

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#936]
**Issue:**
When you are running Uplink without the release flag it is very slow when doing anything on the app like switching chats, going to files, sending a message/friend request etc etc 

**OS:**
All

**STR:**
Simply run Uplink and click through it 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/219ae315-c13e-4d99-a73b-17a679ac789f

**Comment by tooshel** [comment]
I noticed the same on Windows. Are you seeing that on all platforms? Windows, Mac, and maybe even Linux? Any way we can quantify that and compare it to how it was before?

**Comment by dariusc93** [comment]
@phillsatellite is this still a problem since #932 was merged?
