### ISSUE TITLE
fix(ui): Markdown styles not appearing in sidebar

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#946]
**Issue:**
When you add a markdown within the chat, it will not be styled in the sidebar 

**OS:**
All

**Screenshot:**

<img width="959" alt="Screenshot 2023-06-29 at 9 57 17 AM" src="https://github.com/Satellite-im/Uplink/assets/93608357/21458a0d-6faa-4594-ab8a-58ce7b88b897">

**Comment by dariusc93** [comment]
Do we want it to style in the sidebar too or do we want to just filter out the markdown and display text in the sidebar?
