### ISSUE TITLE
feat(calling): implement mockups for direct and group calls

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Uplink#956]
media player in `components/media` currently plays a sample video. Now that calling is possible, it would be nice if this page was displayed when someone answers a call. 

when there isn't a video stream to display, the user's profile picture could be displayed. 

For group calls, we probably want to show a grid of profile pictures for now. 

when the user is talking, we probably want to provide some indicator. There is a warp event for this. 

We probably want a button to allow someone to start/stop recording the call too.

Here are the designs: 
https://www.figma.com/file/vYKm91y1PjZPW0NRuzj0u9/Video%2F-Voice-Chat?type=design&node-id=0-1&mode=design&t=lereamWqfiVpR78l-0

- [x] #1177 
- [x] #1178
- [x] #1176 
- [x] #1174

**Comment by tooshel** [comment]
Some of the design work is done . . . anything missing ask @XileHorizon!

https://www.figma.com/file/vYKm91y1PjZPW0NRuzj0u9/Video%2F-Voice-Chat?type=design&node-id=0-1&mode=design&t=lereamWqfiVpR78l-0

**Comment by phillsatellite** [comment]
@sdwoodbury @tooshel can this ticket be closed now?

**Comment by stavares843** [comment]
asking on discord
