### ISSUE TITLE
bug(chat): User has to click to send message after selecting emoji 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#964]
**Issue:**
When the User is typing a message and adds an emoji, they are forced to click the send button instead of being able to use the _enter_ key 

**OS:**
MacOS

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/c5e11237-491a-486c-b541-5d6bc1920fe7

**Comment by Flemmli97** [comment]
I can't reproduce it. but it might a a vm issue? since it seems you are using a vm?

**Comment by stavares843** [comment]
real device, real mac cc @Flemmli97

**Comment by phillsatellite** [comment]
Updated description,I replicated again but now I can now only replicate on MacOS (true OS not VM)

**Comment by lgmarchi** [comment]
I was not able to replicate in OS. 
@stavares843 and @phillsatellite you both can replicate it? are your macbooks M1?

**Comment by phillsatellite** [comment]
Have only been able to replicate on an M2 Macbook today

**Comment by dariusc93** [comment]
Are you able to reproduce this still @phillsatellite ?
