### ISSUE TITLE
Cant close popout after opening first time

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#99]
**Issue:** Other issue I found on Lucas's latest PR. If we Update the UI to be Media Detached when we open the Pop out player, it will not be possible for the User to re open the pop out player using the pop out button. 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/211399716-95a10bee-1907-41d0-a1eb-943c8a1c243d.mov

**Comment by sdwoodbury** [comment]
resolved via #114
