### ISSUE TITLE
feat(reactions): Update reaction UI (No Emoji Picker)

### ISSUE THREAD

**Issue by XileHorizon** [Satellite-im/Uplink#990]
Task: Use the updated mockups to move the message reactions to the context menu.

The emoji bar in the context menu should only display five of the ten available. Once the plus button is pressed, it should reveal the additional five emoji. 

The design can be adjusted as needed. Just message me if changes are needed.

References:

<img src="https://user-images.githubusercontent.com/33043119/253388597-e85002b1-84e4-4e60-bd8c-efdd602f01cd.png" width="200"/>

<img src="https://user-images.githubusercontent.com/33043119/253388709-d7aeaf93-6da6-4da9-b439-a6dc6b2ddd3a.png" width="200"/>

Figma Link:
https://www.figma.com/file/GrAhLmQWA2kfD1Nw9nd24m/Chats-%2F-Landing-Page?type=design&node-id=1152-39949&mode=design&t=YkyV5CfywPdsHkpX-4

**Comment by phillsatellite** [comment]
@XileHorizon  Is this ticket different from what was created here https://github.com/Satellite-im/Uplink/issues/943 ?

**Comment by tooshel** [comment]
This was partially merged in but now we are looking to get the "+" and other emoji options.

**Comment by phillsatellite** [comment]
Can we close? 

<img width="594" alt="Screenshot 2023-08-14 at 4 35 37 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/86310ae2-5688-4ff7-833b-e5124901badc">

**Comment by InfamousVague** [comment]
We need to do some small work here, the + button should not show up if the extension is not present.

**Comment by lgmarchi** [comment]
Plus button is not working more if emoji extension is not present. 

And with emoji lib extension present, it will open emoji picker to select any emoji to react. 

@InfamousVague Can we close this ticket?
